---
sidebar: sidebar 
permalink: faq-cloud-compliance.html 
keywords: faq, frequently asked questions, questions, cloud compliance, data sense 
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= BlueXPの分類に関するよくある質問
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== BlueXP分類サービス

次の質問は、BlueXPの分類について一般的に理解していることを示しています。



=== BlueXPの分類とは何ですか？

BlueXPは、人工知能（AI）ベースのテクノロジを使用して、データのコンテキストを把握し、ストレージシステム全体で機密データを特定できるクラウドサービスです。システムには、BlueXP Canvasに追加した作業環境や、BlueXPの分類でネットワーク経由でアクセスできるさまざまな種類のデータソースを使用できます。 link:faq-cloud-compliance.html#what-sources-of-data-can-be-scanned-with-bluexp-classification["以下の一覧を参照してください"]。

BlueXPは分類されるため、事前定義されたパラメータ（機密情報のタイプやカテゴリなど）を使用して、データプライバシーと機密性に関する新しいデータコンプライアンス規制（GDPR、CCPA、HIPAAなど）に対応できます。



=== BlueXPの分類の仕組み

BlueXPは、人工知能のもう1つのレイヤを、BlueXPシステムやストレージシステムとともに導入します。次に、ボリューム、バケット、データベース、その他のストレージアカウントのデータをスキャンして、見つかったデータ分析のインデックスを作成します。BlueXPの分類では、正規表現とパターンマッチングを中心に構築されている他のソリューションとは異なり、人工知能と自然言語処理の両方が活用されます。

BlueXPの分類では、AIを使用してデータのコンテキストを把握し、正確な検出と分類を実現します。AIは、最新のデータタイプと拡張性を考慮して設計されているため、この目的はAIによって推進されます。また、データコンテキストを理解して、強力で正確な検出と分類を提供します。

link:concept-cloud-compliance.html["BlueXPの分類の仕組みについて詳しくは、こちらをご覧ください"^]。



=== BlueXPに分類される一般的なユースケースを教えてください。

* 個人識別情報（ PII ）を識別します。
* GDPR 、 CCPA 、 HIPAA 、その他のデータプライバシー規制の要件に応じて、データ主体に応じて特定のデータを容易に検索し、レポートを作成できます。
* データプライバシーに関する新しい規制や今後の規制に対応できます。
* データコンプライアンスやプライバシーの規制に準拠
* 従来型システムからクラウドへデータを移行
* データ保持ポリシーに準拠


https://bluexp.netapp.com/netapp-cloud-data-sense["BlueXP分類のユースケースの詳細については、こちらをご覧ください"^]。



=== BlueXPのアーキテクチャはどうですか？

BlueXPはクラウドかオンプレミスかを問わず、単一のサーバ（クラスタ）を任意の場所に導入できます。サーバは標準プロトコルでデータソースに接続し、同じサーバにも導入されているElasticsearchクラスタの結果をインデックス化します。これにより、マルチクラウド環境、クロスクラウド環境、プライベートクラウド環境、オンプレミス環境をサポートできます。



=== サポートされているクラウドプロバイダを教えてください。

BlueXPの分類はBlueXPの一部として機能し、AWS、Azure、GCPをサポートします。これにより、異なるクラウドプロバイダ間で統一されたプライバシー可視性を実現できます。



=== BlueXPにはREST APIがありますか？また、他社製ツールと連携できますか？

BlueXPは、サービスのREST API機能をサポートしています。BlueXPの管理が推奨されない場合は、REST APIを使用してBlueXPの分類などのサービスを使用することもできます。すべてのユーザアクションには、サードパーティのシステムと統合できるREST APIがあります。



=== BlueXPの分類はマーケットプレイスを通じて提供されますか？

はい。BlueXPとBlueXPの分類は、AWS、Azure、GCPのマーケットプレイスで提供されています。



== BlueXPの分類スキャンと分析

ここでは、BlueXPの分類スキャンのパフォーマンスとユーザが利用できる分析について説明します。



=== BlueXPの分類では、どのくらいの頻度でデータがスキャンされますか？

データは頻繁に変更されるため、BlueXPの分類により、データに影響を与えることなくデータが継続的にスキャンされます。データの初回スキャンには時間がかかる場合がありますが、その後のスキャンでは差分変更のみがスキャンされるため、システムのスキャン時間が短縮されます。

link:concept-cloud-compliance.html#how-scans-work["スキャンの仕組みを説明します"]。

データスキャンは、ストレージシステムとデータにほとんど影響を与えません。ただし、影響がごくわずかであっても問題が発生する場合は、「低速」スキャンを実行するようにBlueXPの分類を設定できます。 link:task-reduce-scan-speed.html["スキャン速度を下げる方法を参照してください"]。



=== BlueXPの分類を使用してデータを検索できますか。

BlueXPは、幅広い検索機能を備えており、接続されているすべてのソースから特定のファイルやデータを簡単に検索できます。BlueXPの分類機能を使用すると、メタデータに反映される情報よりも詳細な情報を検索できます。言語に依存しないサービスで、ファイルを読み取ったり、名前やIDなどの機密データの種類を多数分析したりすることもできます。たとえば、構造化データストアと非構造化データストアの両方を検索して、企業ポリシーに違反してデータベースからユーザファイルに漏れた可能性のあるデータを見つけることができます。検索は後で保存できます。ポリシーを作成して、設定した頻度で結果を検索してアクションを実行できます。

対象となるファイルが見つかったら、タグ、作業環境アカウント、バケット、ファイルパス、 カテゴリ（分類から）、ファイルサイズ、最終変更、権限ステータス、重複、 感度レベル、個人データ、ファイル内の機密データタイプ、所有者、ファイルタイプ、ファイルサイズ、作成時刻、 ファイルハッシュ、注意を求めているユーザーにデータが割り当てられたかどうかなど。フィルタを適用して、適切でないスクリーンアウト特性を適用できます。BlueXPの分類では、適切な権限があればファイルの移動や削除を許可するRBACも用意されています。適切な権限がない場合は、適切な権限を持つ組織内のユーザーにタスクを割り当てることができます。



=== BlueXPの分類では、どのような種類の分析が可能ですか？

データソースを視覚的に表現したり、リレーションシップを定義して視覚的に表現したりできます。たとえば、企業内のすべてのデータソース（オンプレミスのシステム、データベース、ファイル共有、S3ストア、OneDrive、 など）。データのコピー、移動、削除、管理が可能になり、ストレージコストを最適化してリスクを軽減できます。ユーザは、どのような機密データが公開されるかを確認することでリスクを軽減でき、強力なデータ保護を実現するための権限を管理するジョブを作成できます。BlueXPの分類では、すべてのタイプのデータも分類されるため、管理者はデータをタイプ別に調査し、そのデータに対してどのようなアクションが実行されたか、いつ実行されたかを確認できます。



=== BlueXPの分類ではレポートが提供されますか？

はい。BlueXPの分類によって提供される情報は、組織内の他の関係者に関連性があるため、レポートを生成して分析情報を共有できます。BlueXPの分類で使用できるレポートは次のとおりです。

プライバシーリスクアセスメントレポート:: データからプライバシーに関する情報を収集し、プライバシーリスクスコアを取得します。 link:task-generating-compliance-reports.html#privacy-risk-assessment-report["詳細はこちら。"^]。
Data Subject Access Request レポート:: データ主体の特定の名前または個人IDに関する情報を含むすべてのファイルのレポートを抽出できます link:task-generating-compliance-reports.html#what-is-a-data-subject-access-request["詳細はこちら。"^]。
PCI DSS レポート:: クレジットカード情報のファイルへの配布を識別するのに役立ちます。 link:task-generating-compliance-reports.html#pci-dss-report["詳細はこちら。"^]。
HIPAA レポート:: 健常性情報がファイルにどのように分散されているかを確認できます。 link:task-generating-compliance-reports.html#hipaa-report["詳細はこちら。"^]。
データマッピングレポート:: 作業環境内のファイルのサイズと数について説明します。これには、使用容量、データの経過時間、データのサイズ、ファイルタイプが含まれます。 link:task-controlling-governance-data.html#data-mapping-report["詳細はこちら。"^]。
Data Discovery Assessmentレポート:: スキャンされた環境の高度な分析を行い、システムの調査結果を強調し、懸念すべき領域と潜在的な修復手順を示します。 link:task-controlling-governance-data.html#data-discovery-assessment-report["学習モード"^]。
特定の情報タイプに関するレポート:: 個人データや機密性の高い個人データを含む、特定されたファイルの詳細を含むレポートを利用できます。カテゴリおよびファイルタイプ別に分類されたファイルを表示することもできます。 link:task-controlling-private-data.html["詳細はこちら。"^]。




=== スキャンのパフォーマンスは変化しますか？

スキャンのパフォーマンスは、環境内のネットワーク帯域幅と平均ファイルサイズによって異なります。また、（クラウドまたはオンプレミスの）ホストシステムのサイズ特性にも左右されます。を参照してください link:concept-cloud-compliance.html#the-bluexp-classification-instance["BlueXP分類インスタンス"^] および link:task-deploy-cloud-compliance.html["BlueXP分類の導入"^] を参照してください。

新しいデータソースを最初に追加するときに、「分類」のフルスキャンではなく「マッピング」スキャンのみを実行するように選択することもできます。データソースでは、ファイルにアクセスしてデータを参照できないため、マッピングは短時間で完了します。 link:concept-cloud-compliance.html#whats-the-difference-between-mapping-and-classification-scans["マッピングスキャンと分類スキャンの違いを参照してください"^]。



== BlueXPの分類管理とプライバシー

ここでは、BlueXPの分類とプライバシー設定の管理方法について説明します。



=== BlueXPの分類を有効にする方法を教えてください。

まず、BlueXP分類のインスタンスをBlueXPまたはオンプレミスシステムに導入する必要があります。インスタンスが実行されると、*[設定]*タブから、または特定の作業環境を選択して、既存の作業環境、データベース、およびその他のデータソースに対してサービスを有効にできます。

link:task-getting-started-compliance.html["開始方法をご確認ください"^]。


NOTE: データソースでBlueXPの分類をアクティブ化すると、すぐに初回スキャンが実行されます。スキャン結果はすぐ後に表示されます。



=== BlueXPの分類を無効にする方法を教えてください。

BlueXPの分類設定ページでは、個 々 の作業環境、データベース、ファイル共有グループ、OneDriveアカウント、またはSharePointアカウントをスキャンして、BlueXPの分類を無効にすることができます。

link:task-managing-compliance.html["詳細はこちら。"^]。


NOTE: BlueXP分類インスタンスを完全に削除するには、クラウドプロバイダのポータルまたはオンプレミスの場所からBlueXP分類インスタンスを手動で削除します。



=== 組織のニーズに合わせてサービスをカスタマイズできますか。

BlueXPは分類されているため、すぐに使用できる分析情報をデータに提供します。これらの分析情報を抽出して、組織のニーズに活用できます。

さらに、BlueXPの分類では、BlueXPの分類によってスキャンで識別される「個人データ」のカスタムリストを追加することができます。これにより、機密性の高いデータが_all_組織のファイル内のどこにあるかを全体的に把握できます。

* スキャンするデータベースの特定の列に基づいて一意の識別子を追加できます。この* Data Fusion *を呼び出します。
* テキストファイルからカスタムキーワードを追加できます。
* カスタムパターンは、正規表現（regex）を使用して追加できます。


link:task-managing-data-fusion.html["詳細はこちら。"^]。



=== BlueXPの分類情報を特定のユーザに限定できますか。

はい。BlueXPはBlueXPに完全に統合されています。BlueXPユーザーは'ワークスペース権限に応じて表示可能な作業環境の情報のみを表示できます

また、BlueXPの分類設定を管理せずに、特定のユーザにBlueXPの分類スキャン結果だけを表示させる場合は、それらのユーザにCloud Compliance Viewerロールを割り当てることができます。

link:concept-cloud-compliance.html#user-access-to-compliance-information["詳細はこちら。"^]。



=== ブラウザとBlueXPの分類の間で送信されたプライベートデータに誰でもアクセスできますか？

いいえブラウザとBlueXP分類インスタンスの間で送信されるプライベートデータはエンドツーエンドの暗号化で保護されます。つまり、ネットアップやサードパーティはデータを読み取ることができません。BlueXPの分類では、アクセスをリクエストして承認しないかぎり、ネットアップとデータや結果が共有されることはありません。



=== ONTAP ボリュームでデータ階層化が有効になっている場合、どうなりますか？

BlueXPの分類では、コールドデータがオブジェクトストレージに階層化されたボリュームをスキャンするときに、ローカルディスクにあるデータとオブジェクトストレージに階層化されたコールドデータのすべてのデータがスキャンされます。これは、階層化を実装する他社製品にも当てはまります。

スキャンによってコールドデータが加熱されることはなく、コールドデータはオブジェクトストレージに残ります。



=== BlueXPの分類から組織に通知を送信できますか？

はい。ポリシー機能と組み合わせることで、BlueXPユーザー(毎日、毎週、または毎月)、またはポリシーが結果を返したときに電子メールアラートを送信して、データを保護するための通知を受け取ることができます。の詳細を確認してください link:task-using-policies.html["ポリシー"^]。

また、 [ ガバナンス ] ページと [ 調査 ] ページからステータスレポートをダウンロードして、組織内で共有することもできます。



=== BlueXPの分類は、ファイルに埋め込まれたAIPラベルでも機能しますか？

はい。サブスクライブ済みの場合は、BlueXP分類でスキャンするファイルでAIPラベルを管理できます https://azure.microsoft.com/en-us/services/information-protection/["Azure 情報保護（ AIP ）"^]。既にファイルに割り当てられているラベルを表示したり、ファイルにラベルを追加したり、既存のラベルを変更したりできます。

link:task-org-private-data.html#categorizing-your-data-using-aip-labels["詳細はこちら。"^]。



== ソースシステムとデータタイプのタイプ

スキャン可能なストレージのタイプ、およびスキャンするデータのタイプに関連する情報を次に示します。



=== BlueXPでは、どのようなデータソースをスキャンできますか？

BlueXPの分類では、BlueXP Canvasに追加した作業環境や、BlueXPの分類がネットワーク経由でアクセスできるさまざまな種類の構造化/非構造化データソースのデータをスキャンできます。

* 作業環境： *

* Cloud Volumes ONTAP （ AWS 、 Azure 、 GCP に導入）
* オンプレミスの ONTAP クラスタ
* Azure NetApp Files の特長
* ONTAP 対応の Amazon FSX
* Amazon S3


* データソース： *

* ネットアップ以外のファイル共有
* オブジェクトストレージ（ S3 プロトコルを使用）
* データベース（Amazon RDS、MongoDB、MySQL、Oracle、PostgreSQL、 SAP HANA、SQL Serverなど）
* OneDrive アカウント
* SharePoint Onlineアカウントとオンプレミスアカウント
* Googleドライブアカウント


BlueXPの分類では、NFSバージョン3.x、4.0、4.1、CIFSバージョン1.x、2.0、2.1、3.0がサポートされます。



=== 政府機関に導入した場合、制限はありますか？

BlueXPの分類は、コネクタが政府機関のリージョン（AWS GovCloud、Azure Gov、Azure DoD）に導入されている場合にサポートされます。この方法で導入した場合、BlueXPには次の制限があります。

* OneDriveアカウント、SharePointアカウント、Googleドライブアカウントはスキャンできません。
* Microsoft Azure Information Protection（AIP）ラベル機能を統合できません。




=== インターネットにアクセスできないサイトにBlueXP分類をインストールすると、どのようなデータソースをスキャンできますか？

BlueXPの分類では、オンプレミスサイトのローカルなデータソースのデータのみをスキャンできます。現時点では、BlueXPの分類では「ダーク」サイト内の次のローカルデータソースをスキャンできます。

* オンプレミスの ONTAP システム
* データベーススキーマ
* SharePointオンプレミスアカウント(SharePoint Server)
* ネットアップ以外の NFS または CIFS ファイル共有
* Simple Storage Service （ S3 ）プロトコルを使用するオブジェクトストレージ




=== サポートされているファイルタイプはどれですか。

BlueXPの分類は、すべてのファイルをスキャンしてカテゴリやメタデータの分析情報を取得し、ダッシュボードの[File Types]セクションにすべてのファイルタイプを表示します。

BlueXPの分類でPersonal Identifiable Information（PII）が検出された場合、またはDSAR検索が実行された場合、サポートされるファイル形式は次のとおりです。

「+.csv」、「.dcm」、「.dom」、「.DOC」、「.DOCX」、 .json、.pdf、.PPTX、.rtf、.TXT、 .XLS、.xlsx、Docs、Sheets、Slides +`



=== BlueXPの分類では、どのような種類のデータやメタデータがキャプチャされますか？

BlueXPの分類を使用すると、一般的な「マッピング」スキャンまたは完全な「分類」スキャンをデータソースに対して実行できます。マッピングではデータの概要のみが示され、分類ではデータの詳細なスキャンが提供されます。データソースでは、ファイルにアクセスしてデータを参照できないため、マッピングは短時間で完了します。

* データマッピングスキャン：
+
BlueXPの分類では、メタデータのみがスキャンされます。これは、全体的なデータ管理とガバナンス、プロジェクトの迅速な範囲設定、非常に大規模な環境、優先順位付けに役立ちます。データマッピングはメタデータに基づいており、*高速*スキャンとみなされます。

+
高速スキャンの後、データマッピングレポートを生成できます。このレポートは、企業データソースに保存されているデータの概要を示しており、リソースの使用率、移行、バックアップ、セキュリティ、コンプライアンスの各プロセスに関する決定に役立ちます。

* データ分類（ディープ）スキャン。
+
BlueXPの分類では、環境全体で標準プロトコルと読み取り専用権限を使用してスキャンが実行されます。一部のファイルは、ビジネスに関連する機密データ、プライベート情報、ランサムウェアに関連する問題の有無をチェックして開きます。

+
フルスキャン後は、[Data Investigation]ページでのデータの表示と絞り込み、ファイル内の名前の検索、ソースファイルのコピー、移動、削除など、データに適用できるBlueXPの分類機能が多数用意されています。





== ライセンスとコスト

ここでは、BlueXPを使用するためのライセンスとコストについて説明します。



=== BlueXPの分類にはどれくらいのコストがかかりますか？

BlueXPの分類を使用するコストは、スキャンするデータの量によって異なります。BlueXPワークスペースでBlueXPの分類によってスキャンされる最初の1TBのデータは30日間無料です。いずれかの制限に達すると、データのスキャンを続行するために次のいずれかが必要になります。

* クラウドプロバイダからのBlueXP Marketplaceへのサブスクリプション、または
* ネットアップが提供するお客様所有のライセンス（BYOL）


を参照してください https://bluexp.netapp.com/pricing["価格設定"^] を参照してください。



=== BYOLの容量制限に達した場合はどうなりますか？

BYOLの容量が上限に達すると、BlueXPの分類は引き続き実行されますが、ダッシュボードへのアクセスはブロックされるため、スキャンしたデータに関する情報を表示できません。スキャンするボリューム数を減らして容量の使用率をライセンスの上限まで下げる場合は、設定ページのみが表示されます。BlueXPの分類にフルアクセスできるようにするには、BYOLライセンスを更新する必要があります。



== コネクタの展開

次の質問は、BlueXPコネクタに関連しています。



=== コネクタは何ですか？

Connectorは、クラウドアカウントまたはオンプレミスのいずれかのコンピューティングインスタンス上で実行されるソフトウェアで、BlueXPでクラウドリソースを安全に管理できます。BlueXP分類を使用するには、コネクタを導入する必要があります。



=== コネクタはどこに取り付ける必要がありますか？

* AWS 、 Amazon FSX for ONTAP 、または AWS S3 バケット内の Cloud Volumes ONTAP のデータをスキャンするときは、 AWS のコネクタを使用します。
* Azure または Azure NetApp Files で Cloud Volumes ONTAP 内のデータをスキャンする場合は、 Azure のコネクタを使用します。
* GCP の Cloud Volumes ONTAP でデータをスキャンする場合は、 GCP のコネクタを使用します。
* オンプレミスのONTAP システム、ネットアップ以外のファイル共有、汎用のS3オブジェクトストレージ、データベース、OneDriveフォルダ、SharePointアカウント、Google Driveアカウント内のデータをスキャンする場合、これらのクラウド環境ではコネクタを使用できます。


そのため、これらの場所の多くにデータがある場合は、を使用する必要があります https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html#when-to-use-multiple-connectors["複数のコネクタ"^]。



=== コネクタを自分のホストに導入できますか。

はい。可能です https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-install-connector-on-prem.html["コネクタをオンプレミスに導入"^] ネットワーク内のLinuxホストまたはクラウド内のホスト。BlueXP分類をオンプレミスに導入する予定の場合は、コネクタもオンプレミスにインストールすることを推奨しますが、必須ではありません。



=== インターネットにアクセスできないセキュアなサイトはどうでしょうか。

はい、サポートされています。可能です https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-private-mode.html["インターネットにアクセスできないオンプレミスのLinuxホストにコネクタを導入します"^]。その後、オンプレミスのONTAP クラスタとその他のローカルデータソースを検出し、BlueXPの分類を使用してデータをスキャンできます。



== BlueXPクラシフィケーション環境

ここでは、個別のBlueXP分類インスタンスに関連する質問を示します。



=== BlueXPの分類では、どのような導入モデルがサポートされますか？

BlueXPを使用すると、オンプレミス、クラウド、ハイブリッド環境など、ほぼすべての場所でシステムのスキャンとレポートを実行できます。BlueXPは通常、SaaSモデルを使用して導入されます。このモデルでは、BlueXPインターフェイスを介してサービスが有効になり、ハードウェアやソフトウェアのインストールは必要ありません。このクリックアンドランの導入モードであっても、データストアがオンプレミスとパブリッククラウドのどちらにあるかに関係なく、データ管理を実行できます。



=== BlueXPの分類には、どのようなタイプのインスタンスやVMが必要ですか？

いつ link:task-deploy-cloud-compliance.html["クラウドに導入"]：

* AWSでは、BlueXPの分類は、500GiBのgp2ディスクを含むm6i.4xlargeインスタンスで実行されます。導入時に小さいインスタンスタイプを選択できます。
* Azureでは、BlueXPの分類は、ディスクが500GiBのStandard_D16s_v3 VMで実行されます。
* GCPでは、BlueXPの分類は、500GiB Standard永続ディスクを搭載したn2-standard-16 VMで実行されます。


CPUとRAMの数が少ないシステムにBlueXPの分類を導入できますが、これらのシステムを使用する場合は制限があります。を参照してください link:concept-cloud-compliance.html#using-a-smaller-instance-type["小さいインスタンスタイプを使用しています"] を参照してください。

link:concept-cloud-compliance.html["BlueXPの分類の仕組みについて詳しくは、こちらをご覧ください"^]。



=== BlueXP分類を独自のホストに導入できますか。

はい。ネットワークまたはクラウドでインターネットにアクセスできるLinuxホストにBlueXP分類ソフトウェアをインストールできます。すべてが同じように動作し、BlueXPを使用してスキャン設定と結果を引き続き管理できます。を参照してください link:task-deploy-compliance-onprem.html["BlueXPの分類をオンプレミスに導入"] を参照してください。



=== インターネットにアクセスできないセキュアなサイトはどうでしょうか。

はい、サポートされています。可能です link:task-deploy-compliance-dark-site.html["インターネットにアクセスできないオンプレミスサイトにBlueXPを分類して導入します"] 完全にセキュアなサイトに。
