---
sidebar: sidebar 
permalink: faq-cloud-compliance.html 
keywords: faq, frequently asked questions, questions, cloud compliance, data sense 
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= クラウドデータの意味についてよく寄せられる質問
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== Cloud Data Senseサービス

以下の質問は、クラウドデータの意味についての一般的な理解を示しています。



=== クラウドデータの意味

クラウドデータセンスは、人工知能（AI）ベースのテクノロジを使用して、データの状況を把握し、ストレージシステム全体で機密データを特定するクラウドサービスです。システムは、BlueXP Canvasに追加した作業環境や、データがネットワーク上でアクセスできる多くの種類のデータソースになります。 link:faq-cloud-compliance.html#what-sources-of-data-can-be-scanned-with-data-sense["以下の一覧を参照してください"]。

Cloud Data Sense は、事前定義されたパラメータ（機密情報の種類やカテゴリなど）を提供し、 GDPR 、 CCPA 、 HIPAA などのデータプライバシーと機密性に関する新しいデータコンプライアンス規制に対応します。



=== クラウドデータはどのように動作するのでしょうか。

Cloud Data Senseは、BlueXPシステムとストレージシステムに加えて、もう1つの人工知能レイヤを導入します。次に、ボリューム、バケット、データベース、その他のストレージアカウントのデータをスキャンして、見つかったデータ分析のインデックスを作成します。データセンスは、正規表現やパターンマッチングを中心に構築される代替ソリューションとは対照的に、人工知能と自然言語処理の両方を活用します。Cloud Data Senseは、AIを使用してデータをコンテキストに基づいて把握し、正確な検出と分類を行います。AIは、最新のデータタイプと拡張性を考慮して設計されているため、この目的はAIによって推進されます。また、データコンテキストを理解して、強力で正確な検出と分類を提供します。

link:concept-cloud-compliance.html["Cloud Data Sense の仕組みの詳細はこちらをご覧ください"^]。



=== クラウドデータの意味でよく使用されるユースケースはどれですか？

* 個人識別情報（ PII ）を識別します。
* GDPR 、 CCPA 、 HIPAA 、その他のデータプライバシー規制の要件に応じて、データ主体に応じて特定のデータを容易に検索し、レポートを作成できます。
* データプライバシーに関する新しい規制や今後の規制に対応できます。
* データコンプライアンスやプライバシーの規制に準拠
* 従来型システムからクラウドへデータを移行
* データ保持ポリシーに準拠


https://cloud.netapp.com/netapp-cloud-data-sense["Cloud Data Sense のユースケースについて詳しくは、こちらをご覧ください"^]。



=== クラウドデータのアーキテクチャについてどう思いますか？

クラウドデータセンスでは、クラウド内でもオンプレミスでも、単一のサーバまたはクラスタをどこにでも導入できます。サーバは標準プロトコルでデータソースに接続し、同じサーバにも導入されているElasticsearchクラスタの結果をインデックス化します。これにより、マルチクラウド環境、クロスクラウド環境、プライベートクラウド環境、オンプレミス環境をサポートできます。



=== サポートされているクラウドプロバイダを教えてください。

Cloud Data Senseは、BlueXPの一部として動作し、AWS、Azure、GCPをサポートします。これにより、異なるクラウドプロバイダ間で統一されたプライバシー可視性を実現できます。



=== クラウドデータセンスにはREST APIが搭載されており、サードパーティのツールと連携できますか。

BlueXPは、サービスのREST API機能をサポートしています。BlueXPが管理の優先ポイントでない場合は、Cloud Data SenseなどのサービスをREST API経由で使用することもできます。すべてのユーザアクションには、サードパーティのシステムと統合できるREST APIがあります。



=== クラウドデータセンスはマーケットプレイスを通じて利用できるか？

はい。BlueXPとCloud Data Senseは、AWS、Azure、GCP Marketplaceから入手できます。



== Cloud Data Senseのスキャンと分析

以下の質問は、クラウドデータセンススキャンのパフォーマンスとユーザーが利用できる分析に関連しています。



=== Cloud Data Sense はどのくらいの頻度でデータをスキャンしますか？

データが頻繁に変更されるため、 Cloud Data Sense は、データに影響を与えることなくデータを継続的にスキャンします。データの初回スキャンには時間がかかる場合がありますが、その後のスキャンでは差分変更のみがスキャンされるため、システムのスキャン時間が短縮されます。

link:concept-cloud-compliance.html#how-scans-work["スキャンの仕組みを説明します"]。

データスキャンは、ストレージシステムとデータにほとんど影響を与えません。ただし、影響が非常に小さい場合でも、低速スキャンを実行するようにデータセンスを設定できます。 link:task-reduce-scan-speed.html["スキャン速度を下げる方法を参照してください"]。



=== Cloud Data Senseを使ってデータを検索できますか？

Cloud Data Senseは、接続されているすべてのソースで特定のファイルやデータを簡単に検索できるように、幅広い検索機能を提供しています。データセンスを使用すると、メタデータに反映される情報だけでなく、より詳細な情報も検索できます。言語に依存しないサービスで、ファイルを読み取ったり、名前やIDなどの機密データの種類を多数分析したりすることもできます。たとえば、構造化データストアと非構造化データストアの両方を検索して、企業ポリシーに違反してデータベースからユーザファイルに漏れた可能性のあるデータを見つけることができます。検索は後で保存できます。ポリシーを作成して、設定した頻度で結果を検索してアクションを実行できます。

対象となるファイルが見つかったら、タグ、作業環境アカウント、バケット、ファイルパス、 カテゴリ（分類から）、ファイルサイズ、最終変更、権限ステータス、重複、 感度レベル、個人データ、ファイル内の機密データタイプ、所有者、ファイルタイプ、ファイルサイズ、作成時刻、 ファイルハッシュ、注意を求めているユーザーにデータが割り当てられたかどうかなど。フィルタを適用して、適切でないスクリーンアウト特性を適用できます。データセンスには、適切な権限があれば、ファイルの移動や削除を行うためのRBACコントロールもあります。適切な権限がない場合は、適切な権限を持つ組織内のユーザーにタスクを割り当てることができます。



=== Cloud Data Senseは、どのような種類の分析を提供していますか？

データソースを視覚的に表現したり、リレーションシップを定義して視覚的に表現したりできます。たとえば、企業内のすべてのデータソース（オンプレミスのシステム、データベース、ファイル共有、S3ストア、OneDrive、 など）。データのコピー、移動、削除、管理が可能になり、ストレージコストを最適化してリスクを軽減できます。ユーザは、どのような機密データが公開されるかを確認することでリスクを軽減でき、強力なデータ保護を実現するための権限を管理するジョブを作成できます。また、データセンスではさまざまな種類のデータを分類できるため、管理者はデータの種類別にデータを調査し、データに対してどのようなアクションが実行されたのか、いつ実行されたのかを確認できます。



=== Cloud Data Sense はレポートを提供していますか？

はい。Cloud Data Sense が提供する情報は、組織内の他の関係者にも関係があるため、レポートを作成して分析情報を共有することができます。Data Sense で使用できるレポートは次のとおりです。

プライバシーリスクアセスメントレポート:: データからプライバシーに関する情報を収集し、プライバシーリスクスコアを取得します。 link:task-generating-compliance-reports.html#privacy-risk-assessment-report["詳細はこちら。"^]。
Data Subject Access Request レポート:: データサブジェクトの特定の名前または個人 ID に関する情報を含むすべてのファイルのレポートを抽出できます。 link:task-responding-to-dsar.html["詳細はこちら。"^]。
PCI DSS レポート:: クレジットカード情報のファイルへの配布を識別するのに役立ちます。 link:task-generating-compliance-reports.html#pci-dss-report["詳細はこちら。"^]。
HIPAA レポート:: 健常性情報がファイルにどのように分散されているかを確認できます。 link:task-generating-compliance-reports.html#hipaa-report["詳細はこちら。"^]。
データマッピングレポート:: 作業環境内のファイルのサイズと数について説明します。これには、使用容量、データの経過時間、データのサイズ、ファイルタイプが含まれます。 link:task-generating-compliance-reports.html#data-mapping-report["詳細はこちら。"^]。
特定の情報タイプに関するレポート:: 個人データや機密性の高い個人データを含む、特定されたファイルの詳細を含むレポートを利用できます。カテゴリおよびファイルタイプ別に分類されたファイルを表示することもできます。 link:task-controlling-private-data.html["詳細はこちら。"^]。




=== スキャンのパフォーマンスは変化しますか？

スキャンのパフォーマンスは、環境内のネットワーク帯域幅と平均ファイルサイズによって異なります。また、（クラウドまたはオンプレミスの）ホストシステムのサイズ特性にも左右されます。を参照してください link:concept-cloud-compliance.html#the-cloud-data-sense-instance["Cloud Data Sense インスタンス"^] および link:task-deploy-cloud-compliance.html["Cloud Data Sense の導入"^] を参照してください。

新しいデータソースを最初に追加するときに、「分類」のフルスキャンではなく「マッピング」スキャンのみを実行するように選択することもできます。データソースでは、ファイルにアクセスしてデータを参照できないため、マッピングは短時間で完了します。 link:concept-cloud-compliance.html#whats-the-difference-between-mapping-and-classification-scans["マッピングスキャンと分類スキャンの違いを参照してください"^]。



== クラウドデータセンス管理とプライバシー

以下の質問では、クラウドデータのセンスとプライバシーの設定を管理する方法について説明します。



=== クラウドデータセンスを有効にする方法

まず、BlueXPまたはオンプレミスシステムにCloud Data Senseのインスタンスを導入する必要があります。インスタンスの実行が完了したら、既存の作業環境、データベース、およびその他のデータソースに対して、* Data Sense *タブからサービスを有効にするか、特定の作業環境を選択してサービスを有効にすることができます。

link:task-getting-started-compliance.html["開始方法をご確認ください"^]。


NOTE: データソースでCloud Data Senseをアクティブにすると、すぐに初期スキャンが実行されます。スキャン結果はすぐ後に表示されます。



=== クラウドデータセンスを無効にする方法

データセンス構成ページでは、個々の作業環境、データベース、ファイル共有グループ、 OneDrive アカウント、 SharePoint アカウントをスキャンできないようにすることができます。

link:task-managing-compliance.html["詳細はこちら。"^]。


NOTE: クラウドデータセンスインスタンスを完全に削除するには、クラウドプロバイダのポータルまたはオンプレミスの場所から手動でデータセンスインスタンスを削除します。



=== 組織のニーズに合わせてサービスをカスタマイズできますか。

Cloud Data Sense は、すぐに使用できる分析情報をデータに提供します。これらの分析情報を抽出して、組織のニーズに活用できます。

さらに、データセンスは、スキャンで特定される「個人データ」のカスタムリストを追加する方法も多数用意されています。これにより、機密データが存在する可能性のある場所に関する全体像を、_ALL_組織のファイルに表示できます。

* スキャンするデータベースの特定の列に基づいて一意の識別子を追加できます。この* Data Fusion *を呼び出します。
* テキストファイルからカスタムキーワードを追加できます。
* カスタムパターンは、正規表現（regex）を使用して追加できます。


link:task-managing-data-fusion.html["詳細はこちら。"^]。



=== クラウドデータの意味に関する情報を特定のユーザに制限できますか。

はい、Cloud Data SenseはBlueXPと完全に統合されています。BlueXPユーザーは'ワークスペース権限に応じて表示可能な作業環境の情報のみを表示できます

また、データセンス設定を管理しなくても、特定のユーザにデータセンススキャンの結果の表示を許可する場合は、そのユーザにCloud Compliance Viewerロールを割り当てることができます。

link:concept-cloud-compliance.html#user-access-to-compliance-information["詳細はこちら。"^]。



=== ブラウザとデータセンスの間で送信されたプライベートデータに誰でもアクセスできますか。

いいえブラウザとデータセンスインスタンスの間で送信されるプライベートデータはエンドツーエンドの暗号化によって保護されるため、ネットアップとサードパーティが読み取ることはできません。データセンスは、アクセスをリクエストして承認しない限り、データや結果をネットアップと共有しません。



=== ONTAP ボリュームでデータ階層化が有効になっている場合、どうなりますか？

コールドデータをオブジェクトストレージに階層化する ONTAP システムでは、クラウドデータの意味を有効にすることができます。データ階層化が有効になっている場合、データセンスは、ディスクにあるすべてのデータと、オブジェクトストレージに階層化されたコールドデータをスキャンします。

コンプライアンススキャンはコールドデータを加熱しません -- コールドデータを保存し ' オブジェクトストレージに階層化します



=== Cloud Data Sense は、自分の組織に通知を送信できますか？

はい。ポリシー機能と併用すると、ポリシーが結果を返すときに、BlueXPユーザー(毎日、毎週、または毎月)に電子メールアラートを送信して、データを保護するための通知を受け取ることができます。の詳細を確認してください link:task-org-private-data.html#controlling-your-data-using-policies["ポリシー"^]。

また、 [ ガバナンス ] ページと [ 調査 ] ページからステータスレポートをダウンロードして、組織内で共有することもできます。



=== ファイルに埋め込まれた AIP ラベルを使用して Cloud Data Sense を実行できますか。

はい。加入している場合、 Cloud Data Sense がスキャンしているファイルで AIP ラベルを管理できます link:https://azure.microsoft.com/en-us/services/information-protection/["Azure 情報保護（ AIP ）"^]。既にファイルに割り当てられているラベルを表示したり、ファイルにラベルを追加したり、既存のラベルを変更したりできます。

link:task-org-private-data.html#categorizing-your-data-using-aip-labels["詳細はこちら。"^]。



== ソースシステムとデータタイプのタイプ

スキャン可能なストレージのタイプ、およびスキャンするデータのタイプに関連する情報を次に示します。



=== データセンスでスキャンできるデータソースを教えてください。

Cloud Data Senseでは、BlueXP Canvasに追加した作業環境や、データがネットワーク経由でアクセスできる構造化および非構造化データソースからデータをスキャンできます。

* 作業環境： *

* Cloud Volumes ONTAP （ AWS 、 Azure 、 GCP に導入）
* オンプレミスの ONTAP クラスタ
* Azure NetApp Files の特長
* ONTAP 対応の Amazon FSX
* Amazon S3


* データソース： *

* ネットアップ以外のファイル共有
* オブジェクトストレージ（ S3 プロトコルを使用）
* データベース（Amazon RDS、MongoDB、MySQL、Oracle、PostgreSQL、 SAP HANA、SQL Serverなど）
* OneDrive アカウント
* SharePoint Onlineアカウントとオンプレミスアカウント
* Googleドライブアカウント


Data Sense は、 NFS バージョン 3.x 、 4.0 、 4.1 、および CIFS バージョン 1.x 、 2.0 、 2.1 、 3.0 をサポートしています。



=== 政府機関に導入した場合、制限はありますか？

コネクタが政府機関リージョン（AWS GovCloud、Azure Gov、またはAzure DoD）に導入されている場合は、Cloud Data Senseがサポートされます。この方法で展開する場合、データセンスには次の制約があります。

* OneDriveアカウント、SharePointアカウント、Googleドライブアカウントはスキャンできません。
* Microsoft Azure Information Protection（AIP）ラベル機能を統合できません。




=== インターネットにアクセスできないサイトにデータセンスをインストールすると、どのデータソースをスキャンできますか。

データセンスでスキャンできるのは、ローカルのデータソースからオンプレミスのサイトへのデータのみです。現時点では、「ダーク」サイトで次のローカルデータソースをスキャンできます。

* オンプレミスの ONTAP システム
* データベーススキーマ
* SharePointオンプレミスアカウント(SharePoint Server)
* ネットアップ以外の NFS または CIFS ファイル共有
* Simple Storage Service （ S3 ）プロトコルを使用するオブジェクトストレージ




=== サポートされているファイルタイプはどれですか。

Cloud Data Senseは、すべてのファイルをスキャンしてカテゴリやメタデータに関する分析情報を検索し、ダッシュボードのファイルタイプセクションにすべてのファイルタイプを表示します。

データセンスが個人識別情報（PII）を検出した場合、またはdsar検索を実行した場合、次のファイル形式のみがサポートされます。

「+.csv」、「.dcm」、「.dom」、「.DOC」、「.DOCX」、 .json、.pdf、.PPTX、.rtf、.TXT、 .XLS、.xlsx、Docs、Sheets、Slides +`



=== Cloud Dataでは、どのような種類のデータやメタデータをキャプチャできますか？

Cloud Data Senseを使用すると、データソースに対して全般的な「マッピング」スキャンまたは完全な「分類」スキャンを実行できます。マッピングではデータの概要のみが示され、分類ではデータの詳細なスキャンが提供されます。データソースでは、ファイルにアクセスしてデータを参照できないため、マッピングは短時間で完了します。

* データマッピングスキャン：
+
データセンスはメタデータのみをスキャンします。これは、全体的なデータ管理とガバナンス、プロジェクトの迅速な範囲設定、非常に大規模な環境、優先順位付けに役立ちます。データマッピングはメタデータに基づいており、*高速*スキャンとみなされます。

+
高速スキャンの後、データマッピングレポートを生成できます。このレポートは、企業データソースに保存されているデータの概要を示しており、リソースの使用率、移行、バックアップ、セキュリティ、コンプライアンスの各プロセスに関する決定に役立ちます。

* データ分類（ディープ）スキャン。
+
標準プロトコルを使用したデータ検出スキャンと、環境全体での読み取り専用アクセス許可。一部のファイルは、ビジネスに関連する機密データ、プライベート情報、ランサムウェアに関連する問題の有無をチェックして開きます。

+
フルスキャンの後にデータに適用できるデータ検出機能が多数あります。たとえば、[データ調査]ページでのデータの表示とリファイン、ファイル内での名前の検索、ソースファイルのコピー、移動、削除などです。





== ライセンスとコスト

Cloud Data Senseを使用するためのライセンスとコストに関する質問を次に示します。



=== クラウドデータのコストはどれくらいですか？

クラウドデータセンスの使用コストは、スキャンするデータの量によって異なります。BlueXPワークスペースでデータ検出によってスキャンされた最初の1 TBのデータは無料です。この制限に達すると、1TBを超えるデータのスキャンを続行するために次のいずれかが必要になります。

* クラウドプロバイダからのBlueXP Marketplaceへのサブスクリプション、または
* ネットアップが提供するお客様所有のライセンス（BYOL）


を参照してください https://cloud.netapp.com/netapp-cloud-data-sense#Pricing["価格設定"^] を参照してください。



=== BYOLの容量制限に達した場合はどうなりますか？

BYOLの容量制限に達すると、データセンスは引き続き実行されますが、ダッシュボードへのアクセスはブロックされるため、スキャンしたデータに関する情報を表示することはできません。スキャンするボリューム数を減らして容量の使用率をライセンスの上限まで下げる場合は、設定ページのみが表示されます。データセンスへのフルアクセスを回復するには、BYOLライセンスを更新する必要があります。



== コネクタの展開

次の質問は、BlueXPコネクタに関連しています。



=== コネクタは何ですか？

Connectorは、クラウドアカウントまたはオンプレミスのいずれかのコンピューティングインスタンス上で実行されるソフトウェアで、BlueXPでクラウドリソースを安全に管理できます。クラウドデータセンスを使用するには、コネクタを導入する必要があります。



=== コネクタはどこに取り付ける必要がありますか？

* AWS 、 Amazon FSX for ONTAP 、または AWS S3 バケット内の Cloud Volumes ONTAP のデータをスキャンするときは、 AWS のコネクタを使用します。
* Azure または Azure NetApp Files で Cloud Volumes ONTAP 内のデータをスキャンする場合は、 Azure のコネクタを使用します。
* GCP の Cloud Volumes ONTAP でデータをスキャンする場合は、 GCP のコネクタを使用します。
* オンプレミスのONTAP システム、ネットアップ以外のファイル共有、汎用のS3オブジェクトストレージ、データベース、OneDriveフォルダ、SharePointアカウント、Google Driveアカウント内のデータをスキャンする場合、これらのクラウド環境ではコネクタを使用できます。


そのため、これらの場所の多くにデータがある場合は、を使用する必要があります https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html#when-to-use-multiple-connectors["複数のコネクタ"]。



=== コネクタを自分のホストに導入できますか。

はい。可能です https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-installing-linux.html["コネクタをオンプレミスに導入"^] 自社ネットワーク内またはクラウド内の Linux ホストオンプレミスにデータセンスを導入する場合は、オンプレミスにもコネクタをインストールできますが、必須ではありません。



=== インターネットにアクセスできないセキュアなサイトはどうでしょうか。

はい、サポートされています。可能です https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-install-connector-onprem-no-internet.html["インターネットにアクセスできないオンプレミスのLinuxホストにコネクタを導入します"^]。その上で、オンプレミスのONTAP クラスタやその他のローカルデータソースを検出し、データセンスを使用してデータをスキャンすることができます。



== データセンスの導入

以下の質問は、個別のData Senseインスタンスに関連しています。



=== Cloud Data Senseがサポートしている導入モデルを教えてください。

BlueXPを使用すると、オンプレミス、クラウド、ハイブリッド環境など、ほぼすべての場所でシステムのスキャンとレポートを実行できます。通常、Cloud Data SenseはSaaSモデルを使用して導入されます。このモデルでは、サービスはBlueXPインターフェイスを介して有効になり、ハードウェアやソフトウェアをインストールする必要はありません。このクリックアンドランの導入モードであっても、データストアがオンプレミスとパブリッククラウドのどちらにあるかに関係なく、データ管理を実行できます。



=== クラウドデータセンスにはどのようなタイプのインスタンスまたは VM が必要ですか。

いつ link:task-deploy-cloud-compliance.html["クラウドに導入"]：

* AWS では、 Cloud Data Sense は、 500 GB の gp2 ディスクを使用する m5.-m構築 インスタンスで実行されます。
* Azure では、 Cloud Data Sense は、 512 GB のディスクを搭載した Standard_D16s_v3 VM で実行されます。
* GCP では、クラウドデータセンスは、 512 GB の標準永続ディスクを搭載した n2 標準の -16 VM で実行されます。


CPU 数と RAM 容量が少ないシステムには Data Sense を導入できますが、これらのシステムの使用には制限があります。を参照してください link:concept-cloud-compliance.html#using-a-smaller-instance-type["小さいインスタンスタイプを使用しています"] を参照してください。

link:concept-cloud-compliance.html["Cloud Data Sense の仕組みの詳細はこちらをご覧ください"^]。



=== データセンスを自分のホストに導入できますか。

はい。データセンスソフトウェアは、ネットワーク内またはクラウド内でインターネットにアクセスできる Linux ホストにインストールできます。すべてが同じように動作し、BlueXPを使用してスキャン設定と結果を引き続き管理できます。を参照してください link:task-deploy-compliance-onprem.html["クラウドデータセンスをオンプレミスに導入"] を参照してください。



=== インターネットにアクセスできないセキュアなサイトはどうでしょうか。

はい、サポートされています。可能です link:task-deploy-compliance-dark-site.html["インターネットにアクセスできないオンプレミスサイトにデータセンスを導入する"] 完全にセキュアなサイトに。
