---
sidebar: sidebar 
permalink: faq-cloud-compliance.html 
keywords: faq, frequently asked questions, questions, cloud compliance, data sense 
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= BlueXPの分類に関するよくある質問
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== BlueXP分類サービス

次の質問は、BlueXPの分類について一般的に理解していることを示しています。



=== BlueXPの分類の仕組み

BlueXP  分類では、BlueXP  システムやストレージシステムに加えて、AIのもう1つのレイヤが導入されます。次に、ボリューム、バケット、データベース、その他のストレージアカウントのデータをスキャンして、見つかったデータ分析のインデックスを作成します。BlueXPの分類では、正規表現とパターンマッチングを中心に構築されている他のソリューションとは異なり、人工知能と自然言語処理の両方が活用されます。

BlueXPの分類では、AIを使用してデータのコンテキストを把握し、正確な検出と分類を実現します。AIは、最新のデータタイプと拡張性を考慮して設計されているため、この目的はAIによって推進されます。また、データコンテキストを理解して、強力で正確な検出と分類を提供します。

link:concept-cloud-compliance.html["BlueXPの分類の仕組みについて詳しくは、こちらをご覧ください"]です。



=== BlueXPにはREST APIがありますか？また、他社製ツールと連携できますか？

はい。BlueXP  分類には、BlueXP  コアプラットフォームの一部であるBlueXP  分類バージョンでサポートされている機能用のREST APIがあります。を参照して link:api-classification.html["APIのドキュメント"]



=== BlueXP  の分類は、クラウドマーケットプレイスを通じて利用できますか。

BlueXP  の分類はBlueXP  のコア機能の一部であるため、このサービスのマーケットプレイスを使用する必要はありません。



== BlueXPの分類スキャンと分析

以下の質問は、BlueXP  分類スキャンのパフォーマンスと分析に関するものです。



=== BlueXPの分類では、どのくらいの頻度でデータがスキャンされますか？

データの最初のスキャンには少し時間がかかることがありますが、その後のスキャンでは増分変更のみが検査されるため、システムスキャン時間が短縮されます。BlueXPの分類では、データがラウンドロビン方式で継続的にスキャンされ、一度に6つのリポジトリがスキャンされるため、変更されたすべてのデータが非常に迅速に分類されます。

link:task-scanning-overview.html["スキャンの仕組みを説明します"]です。

BlueXP  分類では、データベースが1日に1回だけスキャンされます。データベースは他のデータソースのように継続的にスキャンされることはありません。

データスキャンは、ストレージシステムとデータにほとんど影響を与えません。



=== スキャンのパフォーマンスは変化しますか？

スキャンのパフォーマンスは、環境内のネットワーク帯域幅と平均ファイルサイズによって異なります。また、（クラウドまたはオンプレミスの）ホストシステムのサイズ特性にも左右されます。詳細については、およびを参照してください link:concept-cloud-compliance.html["BlueXP分類インスタンス"] link:task-deploy-overview.html["BlueXP分類の導入"] 。

新しいデータソースを最初に追加するときは、完全な「分類」（Map & Classify）スキャンではなく、「マッピング」（マッピングのみ）スキャンのみを実行するように選択することもできます。データソースでは、ファイルにアクセスしてデータを参照できないため、マッピングは短時間で完了します。link:task-scanning-overview.html["マッピングスキャンと分類スキャンの違いを参照してください"]です。



=== BlueXPの分類を使用してデータを検索できますか。

BlueXPは、幅広い検索機能を備えており、接続されているすべてのソースから特定のファイルやデータを簡単に検索できます。BlueXPの分類機能を使用すると、メタデータに反映される情報よりも詳細な情報を検索できます。言語に依存しないサービスで、ファイルを読み取ったり、名前やIDなどの機密データの種類を多数分析したりすることもできます。たとえば、構造化データストアと非構造化データストアの両方を検索して、企業ポリシーに違反してデータベースからユーザファイルに漏れた可能性のあるデータを見つけることができます。検索は後で保存できます。ポリシーを作成して、設定した頻度で結果を検索してアクションを実行できます。

対象となるファイルが見つかったら、タグ、作業環境アカウント、バケット、ファイルパス、 カテゴリ（分類から）、ファイルサイズ、最終変更、権限ステータス、重複、 感度レベル、個人データ、ファイル内の機密データタイプ、所有者、ファイルタイプ、ファイルサイズ、作成時刻、 ファイルハッシュ、注意を求めているユーザーにデータが割り当てられたかどうかなど。フィルタを適用して、適切でないスクリーンアウト特性を適用できます。

BlueXP  の分類には、適切な権限がある場合にファイルの移動や削除を許可するロールベースアクセス制御（RBAC）もあります。適切な権限がない場合は、適切な権限を持つ組織内のユーザーにタスクを割り当てることができます。



== BlueXPの分類管理とプライバシー

ここでは、BlueXPの分類とプライバシー設定の管理方法について説明します。



=== BlueXP  分類を有効または無効にする方法を教えてください。

まず、BlueXP分類のインスタンスをBlueXPまたはオンプレミスシステムに導入する必要があります。インスタンスが実行されると、*[設定]*タブから、または特定の作業環境を選択して、既存の作業環境、データベース、およびその他のデータソースに対してサービスを有効にできます。link:task-getting-started-compliance.html["開始方法をご確認ください"]です。


NOTE: データソースでBlueXPの分類をアクティブ化すると、すぐに初回スキャンが実行されます。スキャン結果はすぐ後に表示されます。

BlueXPの分類の設定ページでは、個 々 の作業環境、データベース、またはファイル共有グループがスキャンされないように設定できます。を参照して link:task-managing-compliance.html["BlueXPの分類からデータソースを削除します"]

BlueXP分類インスタンスを完全に削除するには、クラウドプロバイダのポータルまたはオンプレミスの場所からBlueXP分類インスタンスを手動で削除します。



=== このサービスでは、特定のディレクトリ内のスキャンデータを除外できますか。

はい。BlueXPの分類で、特定のデータソースディレクトリにあるスキャンデータを除外するには、そのリストを分類エンジンに指定します。この変更を適用すると、BlueXPの分類によって、指定したディレクトリ内のスキャンデータが除外されます。link:task-exclude-scan-paths.html["詳細"]です。



=== ONTAPボリュームにあるSnapshotはスキャンされますか？

いいえ。コンテンツがボリューム内のコンテンツと同じであるため、BlueXP  分類ではSnapshotはスキャンされません。



=== ONTAP ボリュームでデータ階層化が有効になっている場合、どうなりますか？

マッピングのみスキャンを使用してコールドデータをオブジェクトストレージに階層化したボリュームをBlueXP  分類でスキャンすると、ローカルディスクにあるデータとオブジェクトストレージに階層化されたコールドデータのすべてのデータがスキャンされます。これは、階層化を実装する他社製品にも当てはまります。

マッピングのみのスキャンではコールドデータは加熱されず、コールドデータはオブジェクトストレージに残ります。一方、Map & Classifyスキャンを実行すると、一部の構成でコールドデータが加熱される可能性があります。



== ソースシステムとデータタイプのタイプ

スキャン可能なストレージのタイプ、およびスキャンするデータのタイプに関連する情報を次に示します。



=== 政府機関に導入した場合、制限はありますか？

BlueXPの分類は、コネクタが政府機関のリージョン（AWS GovCloud、Azure Gov、Azure DoD）（「制限モード」とも呼ばれます）に導入されている場合にサポートされます。



=== インターネットにアクセスできないサイトにBlueXP分類をインストールすると、どのようなデータソースをスキャンできますか？

BlueXPの分類では、オンプレミスサイトのローカルなデータソースのデータのみをスキャンできます。この時点で、BlueXPの分類では、「プライベートモード」（「ダーク」サイトとも呼ばれます）で次のローカルデータソースをスキャンできます。

* オンプレミスの ONTAP システム
* データベーススキーマ
* Simple Storage Service （ S3 ）プロトコルを使用するオブジェクトストレージ


を参照して link:concept-cloud-compliance.html["サポートされている作業環境とデータソース"]



=== サポートされているファイルタイプはどれですか。

BlueXPの分類は、すべてのファイルをスキャンしてカテゴリやメタデータの分析情報を取得し、ダッシュボードの[File Types]セクションにすべてのファイルタイプを表示します。

BlueXPの分類でPersonal Identifiable Information（PII）が検出された場合、またはDSAR検索が実行された場合、サポートされるファイル形式は次のとおりです。

`+.CSV, .DCM, .DICOM, .DOC, .DOCX, .JSON, .PDF, .PPTX, .RTF, .TXT, .XLS, .XLSX, Docs, Sheets, and Slides+`



=== BlueXPの分類では、どのような種類のデータやメタデータがキャプチャされますか？

BlueXPの分類を使用すると、一般的な「マッピング」スキャンまたは完全な「分類」スキャンをデータソースに対して実行できます。マッピングではデータの概要のみが示され、分類ではデータの詳細なスキャンが提供されます。データソースでは、ファイルにアクセスしてデータを参照できないため、マッピングは短時間で完了します。

* *データマッピングスキャン（マッピングのみスキャン）*：BlueXP  分類はメタデータのみをスキャンします。これは、全体的なデータ管理とガバナンス、プロジェクトの迅速な範囲設定、非常に大規模な環境、優先順位付けに役立ちます。データマッピングはメタデータに基づいており、*高速*スキャンとみなされます。
+
高速スキャンの後、データマッピングレポートを生成できます。このレポートは、企業データソースに保存されているデータの概要を示しており、リソースの使用率、移行、バックアップ、セキュリティ、コンプライアンスの各プロセスに関する決定に役立ちます。

* *データ分類（ディープ）スキャン（マップおよび分類スキャン）*：環境全体で標準プロトコルと読み取り専用権限を使用して、BlueXP  分類スキャンを実行します。一部のファイルは、ビジネスに関連する機密データ、プライベート情報、ランサムウェアに関連する問題の有無をチェックして開きます。
+
フルスキャン後は、[Data Investigation]ページでのデータの表示と絞り込み、ファイル内の名前の検索、ソースファイルのコピー、移動、削除など、データに適用できるBlueXPの分類機能が多数用意されています。



BlueXPの分類では、ファイル名、権限、作成日時、最終アクセス、最終変更日時などのメタデータがキャプチャされます。これには、[Data Investigatcdion Details]ページおよび[Data Investigation Reports]に表示されるすべてのメタデータが含まれます。

BlueXP  の分類は、個人情報(PII)や機密個人情報(SPII)など、多くの種類の個人データを識別することができます。プライベートデータの詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["BlueXPの分類でスキャンされるプライベートデータのカテゴリ"]。



=== BlueXPの分類情報を特定のユーザに限定できますか。

はい。BlueXPはBlueXPに完全に統合されています。BlueXP  ユーザには、権限に応じて表示できる作業環境の情報のみが表示されます。

また、特定のユーザーがBlueXP  分類設定を管理する機能を持たずにBlueXP  分類スキャン結果のみを表示できるようにする場合は、それらのユーザーに*分類ビューア*ロール（標準モードでBlueXP  を使用している場合）または*コンプライアンスビューア*ロール（制限モードでBlueXP  を使用している場合）を割り当てることができます。link:concept-cloud-compliance.html["詳細"]です。



=== ブラウザとBlueXPの分類の間で送信されたプライベートデータに誰でもアクセスできますか？

いいえ。ブラウザとBlueXP  分類インスタンスの間で送信されるプライベートデータは、TLS 1.2を使用したエンドツーエンドの暗号化で保護されています。これは、NetAppと非NetAppの関係者がそれを読み取ることができないことを意味します。BlueXPの分類では、アクセスをリクエストして承認しないかぎり、ネットアップとデータや結果が共有されることはありません。

スキャンされたデータは環境内に保持されます。



=== 機密データはどのように処理されますか？

NetAppは機密データにアクセスできず、UIに表示されません。機密データはマスクされます。たとえば、クレジットカード情報用に最後の4つの数字が表示されます。



=== データはどこに保存されていますか？

スキャン結果は、BlueXP分類インスタンス内のElasticsearchに保存されます。



=== データへのアクセス方法

BlueXPの分類では、Elasticsearchに格納されたデータにAPI呼び出しを通じてアクセスします。API呼び出しは認証を必要とし、AES-128を使用して暗号化されます。Elasticsearchに直接アクセスするにはrootアクセスが必要です。



== ライセンスとコスト

ここでは、BlueXPを使用するためのライセンスとコストについて説明します。



=== BlueXPの分類にはどれくらいのコストがかかりますか？

BlueXPはBlueXPのコア機能であり、料金は発生しません。



== コネクタの展開

次の質問は、BlueXPコネクタに関連しています。



=== コネクタは何ですか？

Connectorは、クラウドアカウントまたはオンプレミスのいずれかのコンピューティングインスタンス上で実行されるソフトウェアで、BlueXPでクラウドリソースを安全に管理できます。BlueXP分類を使用するには、コネクタを導入する必要があります。



=== コネクタはどこに取り付ける必要がありますか？

データをスキャンするときは、BlueXP  Connectorを次の場所にインストールする必要があります。

* AWSのCloud Volumes ONTAPまたはAmazon FSx for ONTAPの場合：コネクタはAWSにあります。
* AzureまたはAzure NetApp FilesのCloud Volumes ONTAPの場合：コネクタはAzureにあります。
* GCP内のCloud Volumes ONTAPの場合：コネクタはGCP内にあります。
* オンプレミスのONTAPシステムの場合：コネクタはオンプレミスです。


これらの場所にデータがある場合は、を使用する必要があり https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#when-to-use-multiple-connectors["複数のコネクタ"^]ます。



=== BlueXPの分類ではクレデンシャルへのアクセスが必要ですか？

BlueXPの分類自体はストレージクレデンシャルを取得しません。代わりに、BlueXPコネクタ内に格納されます。

BlueXPはデータプレーンのクレデンシャル（CIFSクレデンシャルなど）を使用して共有をマウントしてからスキャンを実行します。



=== サービスとコネクタ間の通信にHTTPが使用されていますか？

はい。BlueXPはHTTPを使用してBlueXPコネクタと通信します。



== BlueXPクラシフィケーション環境

ここでは、個別のBlueXP分類インスタンスに関連する質問を示します。



=== BlueXPの分類では、どのような導入モデルがサポートされますか？

BlueXPを使用すると、オンプレミス、クラウド、ハイブリッド環境など、ほぼすべての場所でシステムのスキャンとレポートを実行できます。BlueXPは通常、SaaSモデルを使用して導入されます。このモデルでは、BlueXPインターフェイスを介してサービスが有効になり、ハードウェアやソフトウェアのインストールは必要ありません。このクリックアンドランの導入モードであっても、データストアがオンプレミスとパブリッククラウドのどちらにあるかに関係なく、データ管理を実行できます。



=== BlueXPの分類には、どのようなタイプのインスタンスやVMが必要ですか？

link:task-deploy-cloud-compliance.html["クラウドに導入"]次の場合：

* AWSでは、BlueXPの分類は、500GiBのgp2ディスクを含むm6i.4xlargeインスタンスで実行されます。導入時に小さいインスタンスタイプを選択できます。
* Azureでは、BlueXPの分類は、ディスクが500GiBのStandard_D16s_v3 VMで実行されます。
* GCPでは、BlueXPの分類は、500GiB Standard永続ディスクを搭載したn2-standard-16 VMで実行されます。


link:concept-cloud-compliance.html["BlueXPの分類の仕組みについて詳しくは、こちらをご覧ください"]です。



=== BlueXP分類を独自のホストに導入できますか。

はい。ネットワークまたはクラウドでインターネットにアクセスできるLinuxホストにBlueXP分類ソフトウェアをインストールできます。すべてが同じように動作し、BlueXPを使用してスキャン設定と結果を引き続き管理できます。システム要件およびインストールの詳細については、を参照してくださいlink:task-deploy-compliance-onprem.html["BlueXPの分類をオンプレミスに導入"]。



=== インターネットにアクセスできないセキュアなサイトはどうでしょうか。

はい、サポートされています。あなたは完全に安全なサイトのためにできますlink:task-deploy-compliance-dark-site.html["インターネットにアクセスできないオンプレミスサイトにBlueXPを分類して導入します"]。
