---
sidebar: sidebar 
permalink: faq-cloud-compliance.html 
keywords: faq, frequently asked questions, questions, cloud compliance, data sense 
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= BlueXPの分類に関するよくある質問
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== BlueXP分類サービス

次の質問は、BlueXPの分類について一般的に理解していることを示しています。



=== BlueXPの分類とは何ですか？

BlueXPは、人工知能（AI）ベースのテクノロジを使用して、データのコンテキストを把握し、ストレージシステム全体で機密データを特定できるクラウドサービスです。システムには、BlueXP Canvasに追加した作業環境や、BlueXPの分類でネットワーク経由でアクセスできるさまざまな種類のデータソースを使用できます。 link:faq-cloud-compliance.html#what-sources-of-data-can-be-scanned-with-bluexp-classification["以下の一覧を参照してください"]。

BlueXPは分類されるため、事前定義されたパラメータ（機密情報のタイプやカテゴリなど）を使用して、データプライバシーと機密性に関する新しいデータコンプライアンス規制（GDPR、CCPA、HIPAAなど）に対応できます。



=== BlueXPの分類の仕組み

BlueXPは、人工知能のもう1つのレイヤを、BlueXPシステムやストレージシステムとともに導入します。次に、ボリューム、バケット、データベース、その他のストレージアカウントのデータをスキャンして、見つかったデータ分析のインデックスを作成します。BlueXPの分類では、正規表現とパターンマッチングを中心に構築されている他のソリューションとは異なり、人工知能と自然言語処理の両方が活用されます。

BlueXPの分類では、AIを使用してデータのコンテキストを把握し、正確な検出と分類を実現します。AIは、最新のデータタイプと拡張性を考慮して設計されているため、この目的はAIによって推進されます。また、データコンテキストを理解して、強力で正確な検出と分類を提供します。

link:concept-cloud-compliance.html["BlueXPの分類の仕組みについて詳しくは、こちらをご覧ください"^]。

https://bluexp.netapp.com/netapp-cloud-data-sense["BlueXP分類のユースケースの詳細については、こちらをご覧ください"^]。



=== BlueXPのアーキテクチャはどうですか？

BlueXPはクラウドかオンプレミスかを問わず、単一のサーバ（クラスタ）を任意の場所に導入できます。サーバは標準プロトコルでデータソースに接続し、同じサーバにも導入されているElasticsearchクラスタの結果をインデックス化します。これにより、マルチクラウド環境、クロスクラウド環境、プライベートクラウド環境、オンプレミス環境をサポートできます。



=== サポートされているクラウドプロバイダを教えてください。

BlueXPの分類はBlueXPの一部として機能し、AWS、Azure、GCPをサポートします。これにより、異なるクラウドプロバイダ間で統一されたプライバシー可視性を実現できます。



=== BlueXPにはREST APIがありますか？また、他社製ツールと連携できますか？

いいえ。BlueXPにはREST APIはありません。



=== BlueXPの分類はマーケットプレイスを通じて提供されますか？

はい。BlueXPとBlueXPの分類は、AWS、Azure、GCPのマーケットプレイスで提供されています。



== BlueXPの分類スキャンと分析

ここでは、BlueXPの分類スキャンのパフォーマンスとユーザが利用できる分析について説明します。



=== BlueXPの分類では、どのくらいの頻度でデータがスキャンされますか？

データの最初のスキャンには少し時間がかかることがありますが、その後のスキャンでは増分変更のみが検査されるため、システムスキャン時間が短縮されます。BlueXPの分類では、データがラウンドロビン方式で継続的にスキャンされ、一度に6つのリポジトリがスキャンされるため、変更されたすべてのデータが非常に迅速に分類されます。

link:concept-cloud-compliance.html#how-scans-work["スキャンの仕組みを説明します"]。

BlueXPの分類では、データベースが1日に1回しかスキャンされません。データベースは、他のデータソースのように継続的にスキャンされるわけではありません。

データスキャンは、ストレージシステムとデータにほとんど影響を与えません。ただし、影響がごくわずかであっても問題が発生する場合は、「低速」スキャンを実行するようにBlueXPの分類を設定できます。 link:task-reduce-scan-speed.html["スキャン速度を下げる方法を参照してください"]。



=== BlueXPの分類を使用してデータを検索できますか。

BlueXPは、幅広い検索機能を備えており、接続されているすべてのソースから特定のファイルやデータを簡単に検索できます。BlueXPの分類機能を使用すると、メタデータに反映される情報よりも詳細な情報を検索できます。言語に依存しないサービスで、ファイルを読み取ったり、名前やIDなどの機密データの種類を多数分析したりすることもできます。たとえば、構造化データストアと非構造化データストアの両方を検索して、企業ポリシーに違反してデータベースからユーザファイルに漏れた可能性のあるデータを見つけることができます。検索は後で保存できます。ポリシーを作成して、設定した頻度で結果を検索してアクションを実行できます。

対象となるファイルが見つかったら、タグ、作業環境アカウント、バケット、ファイルパス、 カテゴリ（分類から）、ファイルサイズ、最終変更、権限ステータス、重複、 感度レベル、個人データ、ファイル内の機密データタイプ、所有者、ファイルタイプ、ファイルサイズ、作成時刻、 ファイルハッシュ、注意を求めているユーザーにデータが割り当てられたかどうかなど。フィルタを適用して、適切でないスクリーンアウト特性を適用できます。BlueXPの分類では、適切な権限があればファイルの移動や削除を許可するRBACも用意されています。適切な権限がない場合は、適切な権限を持つ組織内のユーザーにタスクを割り当てることができます。



=== BlueXPの分類ではレポートが提供されますか？

はい。BlueXPの分類によって提供される情報は、組織内の他の関係者に関連性があるため、レポートを生成して分析情報を共有できます。BlueXPの分類で使用できるレポートは次のとおりです。

プライバシーリスクアセスメントレポート:: データからプライバシーに関する情報を収集し、プライバシーリスクスコアを取得します。 link:task-generating-compliance-reports.html#privacy-risk-assessment-report["詳細はこちら。"^]。
Data Subject Access Request レポート:: データ主体の特定の名前または個人IDに関する情報を含むすべてのファイルのレポートを抽出できます link:task-generating-compliance-reports.html#what-is-a-data-subject-access-request["詳細はこちら。"^]。
PCI DSS レポート:: クレジットカード情報のファイルへの配布を識別するのに役立ちます。 link:task-generating-compliance-reports.html#pci-dss-report["詳細はこちら。"^]。
HIPAA レポート:: 健常性情報がファイルにどのように分散されているかを確認できます。 link:task-generating-compliance-reports.html#hipaa-report["詳細はこちら。"^]。
データマッピングレポート:: 作業環境内のファイルのサイズと数について説明します。これには、使用容量、データの経過時間、データのサイズ、ファイルタイプが含まれます。 link:task-controlling-governance-data.html#data-mapping-report["詳細はこちら。"^]。
Data Discovery Assessmentレポート:: スキャンされた環境の高度な分析を行い、システムの調査結果を強調し、懸念すべき領域と潜在的な修復手順を示します。 link:task-controlling-governance-data.html#data-discovery-assessment-report["学習モード"^]。
特定の情報タイプに関するレポート:: 個人データや機密性の高い個人データを含む、特定されたファイルの詳細を含むレポートを利用できます。カテゴリおよびファイルタイプ別に分類されたファイルを表示することもできます。 link:task-controlling-private-data.html["詳細はこちら。"^]。




=== スキャンのパフォーマンスは変化しますか？

スキャンのパフォーマンスは、環境内のネットワーク帯域幅と平均ファイルサイズによって異なります。また、（クラウドまたはオンプレミスの）ホストシステムのサイズ特性にも左右されます。を参照してください link:concept-cloud-compliance.html#the-bluexp-classification-instance["BlueXP分類インスタンス"^] および link:task-deploy-cloud-compliance.html["BlueXP分類の導入"^] を参照してください。

新しいデータソースを最初に追加するときに、「分類」のフルスキャンではなく「マッピング」スキャンのみを実行するように選択することもできます。データソースでは、ファイルにアクセスしてデータを参照できないため、マッピングは短時間で完了します。 link:concept-cloud-compliance.html#whats-the-difference-between-mapping-and-classification-scans["マッピングスキャンと分類スキャンの違いを参照してください"^]。



== BlueXPの分類管理とプライバシー

ここでは、BlueXPの分類とプライバシー設定の管理方法について説明します。



=== BlueXPの分類を有効にする方法を教えてください。

まず、BlueXP分類のインスタンスをBlueXPまたはオンプレミスシステムに導入する必要があります。インスタンスが実行されると、*[設定]*タブから、または特定の作業環境を選択して、既存の作業環境、データベース、およびその他のデータソースに対してサービスを有効にできます。

link:task-getting-started-compliance.html["開始方法をご確認ください"^]。


NOTE: データソースでBlueXPの分類をアクティブ化すると、すぐに初回スキャンが実行されます。スキャン結果はすぐ後に表示されます。



=== BlueXPの分類を無効にする方法を教えてください。

BlueXPの分類の設定ページでは、個 々 の作業環境、データベース、またはファイル共有グループがスキャンされないように設定できます。

link:task-managing-compliance.html["詳細はこちら。"^]。


NOTE: BlueXP分類インスタンスを完全に削除するには、クラウドプロバイダのポータルまたはオンプレミスの場所からBlueXP分類インスタンスを手動で削除します。



=== 組織のニーズに合わせてサービスをカスタマイズできますか。

BlueXPは分類されているため、データの分析情報が得られます。これらの分析情報を抽出して、組織のニーズに活用できます。

さらに、BlueXPの分類では、BlueXPの分類によってスキャンで識別される「個人データ」のカスタムリストを追加することができます。これにより、機密性の高いデータが_all_組織のファイル内のどこにあるかを全体的に把握できます。

* スキャンするデータベースの特定の列に基づいて一意の識別子を追加できます。この* Data Fusion *を呼び出します。
* テキストファイルからカスタムキーワードを追加できます。
* カスタムパターンは、正規表現（regex）を使用して追加できます。


link:task-managing-data-fusion.html["詳細はこちら。"^]。



=== 特定のディレクトリのスキャンデータを除外するようにサービスに指示することはできますか?

はい。BlueXPの分類で、特定のデータソースディレクトリにあるスキャンデータを除外するには、そのリストを分類エンジンに指定します。この変更を適用すると、BlueXPの分類によって、指定したディレクトリ内のスキャンデータが除外されます。

link:task-exclude-scan-paths.html["詳細はこちら。"^]。



=== ONTAPボリュームにあるSnapshotはスキャンされますか？

いいえBlueXPの分類ではSnapshotはスキャンされません。これは、コンテンツがボリューム内のコンテンツと同じであるためです。



=== ONTAP ボリュームでデータ階層化が有効になっている場合、どうなりますか？

BlueXPの分類では、コールドデータがオブジェクトストレージに階層化されたボリュームをスキャンするときに、ローカルディスクにあるデータとオブジェクトストレージに階層化されたコールドデータのすべてのデータがスキャンされます。これは、階層化を実装する他社製品にも当てはまります。

スキャンによってコールドデータが加熱されることはなく、コールドデータはオブジェクトストレージに残ります。



== ソースシステムとデータタイプのタイプ

スキャン可能なストレージのタイプ、およびスキャンするデータのタイプに関連する情報を次に示します。



=== BlueXPでは、どのようなデータソースをスキャンできますか？

BlueXPの分類では、BlueXP Canvasに追加した作業環境や、BlueXPの分類がネットワーク経由でアクセスできるさまざまな種類の構造化/非構造化データソースのデータをスキャンできます。

を参照してください link:concept-cloud-compliance.html["サポートされている作業環境とデータソース"]。



=== 政府機関に導入した場合、制限はありますか？

BlueXPの分類は、コネクタが政府機関のリージョン（AWS GovCloud、Azure Gov、Azure DoD）（「制限モード」とも呼ばれます）に導入されている場合にサポートされます。この方法で導入した場合、BlueXPには次の制限があります。

[]
====
*注*この情報は、BlueXPの旧バージョン1.30以前の分類にのみ関連します。

====
* OneDriveアカウント、SharePointアカウント、Googleドライブアカウントはスキャンできません。
* Microsoft Azure Information Protection（AIP）ラベル機能を統合できません。




=== インターネットにアクセスできないサイトにBlueXP分類をインストールすると、どのようなデータソースをスキャンできますか？

BlueXPの分類では、オンプレミスサイトのローカルなデータソースのデータのみをスキャンできます。この時点で、BlueXPの分類では、「プライベートモード」（「ダーク」サイトとも呼ばれます）で次のローカルデータソースをスキャンできます。

* オンプレミスの ONTAP システム
* データベーススキーマ
* Simple Storage Service （ S3 ）プロトコルを使用するオブジェクトストレージ


を参照してください link:concept-cloud-compliance.html["サポートされている作業環境とデータソース"]。



=== サポートされているファイルタイプはどれですか。

BlueXPの分類は、すべてのファイルをスキャンしてカテゴリやメタデータの分析情報を取得し、ダッシュボードの[File Types]セクションにすべてのファイルタイプを表示します。

BlueXPの分類でPersonal Identifiable Information（PII）が検出された場合、またはDSAR検索が実行された場合、サポートされるファイル形式は次のとおりです。

「+.csv」、「.dcm」、「.dom」、「.DOC」、「.DOCX」、 .json、.pdf、.PPTX、.rtf、.TXT、 .XLS、.xlsx、Docs、Sheets、Slides +`



=== BlueXPの分類では、どのような種類のデータやメタデータがキャプチャされますか？

BlueXPの分類を使用すると、一般的な「マッピング」スキャンまたは完全な「分類」スキャンをデータソースに対して実行できます。マッピングではデータの概要のみが示され、分類ではデータの詳細なスキャンが提供されます。データソースでは、ファイルにアクセスしてデータを参照できないため、マッピングは短時間で完了します。

* *データマッピングスキャン*：BlueXPの分類により、メタデータのみがスキャンされます。これは、全体的なデータ管理とガバナンス、プロジェクトの迅速な範囲設定、非常に大規模な環境、優先順位付けに役立ちます。データマッピングはメタデータに基づいており、*高速*スキャンとみなされます。
+
高速スキャンの後、データマッピングレポートを生成できます。このレポートは、企業データソースに保存されているデータの概要を示しており、リソースの使用率、移行、バックアップ、セキュリティ、コンプライアンスの各プロセスに関する決定に役立ちます。

* *データ分類（ディープ）スキャン*：BlueXPの分類スキャンでは、標準プロトコルと読み取り専用権限を使用して環境全体をスキャンします。一部のファイルは、ビジネスに関連する機密データ、プライベート情報、ランサムウェアに関連する問題の有無をチェックして開きます。
+
フルスキャン後は、[Data Investigation]ページでのデータの表示と絞り込み、ファイル内の名前の検索、ソースファイルのコピー、移動、削除など、データに適用できるBlueXPの分類機能が多数用意されています。



BlueXPの分類では、ファイル名、権限、作成日時、最終アクセス、最終変更日時などのメタデータがキャプチャされます。これには、[Data Investigation Details]ページおよび[Data Investigation Reports]に表示されるすべてのメタデータが含まれます。

BlueXPの分類では、個人情報（PII）や機密性の高い個人情報（SPii）など、さまざまなタイプのプライベートデータを特定できます。プライベートデータの詳細については、を参照してください。 https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["BlueXPの分類でスキャンされるプライベートデータのカテゴリ"]。



=== BlueXPの分類情報を特定のユーザに限定できますか。

はい。BlueXPはBlueXPに完全に統合されています。BlueXP  ユーザには、権限に応じて表示できる作業環境の情報のみが表示されます。

また、特定のユーザーがBlueXP  分類設定を管理する機能を持たずにBlueXP  分類スキャン結果のみを表示できるようにする場合は、それらのユーザーに*分類ビューア*ロール（標準モードでBlueXP  を使用している場合）または*コンプライアンスビューア*ロール（制限モードでBlueXP  を使用している場合）を割り当てることができます。

link:concept-cloud-compliance.html["詳細はこちら。"^]です。



=== ブラウザとBlueXPの分類の間で送信されたプライベートデータに誰でもアクセスできますか？

いいえブラウザとBlueXP分類インスタンスの間で送信されるプライベートデータは、TLS 1.2を使用したエンドツーエンドの暗号化で保護されます。つまり、NetAppやネットアップ以外のユーザはデータを読み取ることができません。BlueXPの分類では、アクセスをリクエストして承認しないかぎり、ネットアップとデータや結果が共有されることはありません。

スキャンされたデータは環境内に保持されます。



=== 機密データはどのように処理されますか？

NetAppは機密データにアクセスできず、UIに表示されません。機密データはマスクされます。たとえば、クレジットカード情報用に最後の4つの数字が表示されます。



=== データはどこに保存されていますか？

スキャン結果は、BlueXP分類インスタンス内のElasticsearchに保存されます。



=== データへのアクセス方法

BlueXPの分類では、Elasticsearchに格納されたデータにAPI呼び出しを通じてアクセスします。API呼び出しは認証を必要とし、AES-128を使用して暗号化されます。Elasticsearchに直接アクセスするにはrootアクセスが必要です。



== ライセンスとコスト

ここでは、BlueXPを使用するためのライセンスとコストについて説明します。



=== BlueXPの分類にはどれくらいのコストがかかりますか？

BlueXPはBlueXPのコア機能であり、料金は発生しません。



== コネクタの展開

次の質問は、BlueXPコネクタに関連しています。



=== コネクタは何ですか？

Connectorは、クラウドアカウントまたはオンプレミスのいずれかのコンピューティングインスタンス上で実行されるソフトウェアで、BlueXPでクラウドリソースを安全に管理できます。BlueXP分類を使用するには、コネクタを導入する必要があります。



=== コネクタはどこに取り付ける必要がありますか？

* AWSのCloud Volumes ONTAPまたはAmazon FSx for ONTAPでデータをスキャンする場合は、AWSのコネクタを使用します。
* Azure または Azure NetApp Files で Cloud Volumes ONTAP 内のデータをスキャンする場合は、 Azure のコネクタを使用します。
* GCP の Cloud Volumes ONTAP でデータをスキャンする場合は、 GCP のコネクタを使用します。
* オンプレミスのONTAPシステム、NetAppファイル共有、データベースのデータをスキャンする場合は、これらのクラウドのいずれかでコネクタを使用できます。


そのため、これらの場所の多くにデータがある場合は、を使用する必要があります https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#when-to-use-multiple-connectors["複数のコネクタ"^]。



=== BlueXPの分類ではクレデンシャルへのアクセスが必要ですか？

BlueXPの分類自体はストレージクレデンシャルを取得しません。代わりに、BlueXPコネクタ内に格納されます。

BlueXPはデータプレーンのクレデンシャル（CIFSクレデンシャルなど）を使用して共有をマウントしてからスキャンを実行します。



=== コネクタを自分のホストに導入できますか。

はい。可能です https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["コネクタをオンプレミスに導入"^] ネットワーク内のLinuxホストまたはクラウド内のホスト。BlueXP分類をオンプレミスに導入する予定の場合は、コネクタもオンプレミスにインストールすることを推奨しますが、必須ではありません。



=== サービスとコネクタ間の通信にHTTPが使用されていますか？

はい。BlueXPはHTTPを使用してBlueXPコネクタと通信します。



=== インターネットにアクセスできないセキュアなサイトはどうでしょうか。

はい、サポートされています。可能です https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["インターネットにアクセスできないオンプレミスのLinuxホストにコネクタを導入します"^]。 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["これは「プライベートモード」とも呼ばれます。"^]。その後、オンプレミスのONTAP クラスタとその他のローカルデータソースを検出し、BlueXPの分類を使用してデータをスキャンできます。



== BlueXPクラシフィケーション環境

ここでは、個別のBlueXP分類インスタンスに関連する質問を示します。



=== BlueXPの分類では、どのような導入モデルがサポートされますか？

BlueXPを使用すると、オンプレミス、クラウド、ハイブリッド環境など、ほぼすべての場所でシステムのスキャンとレポートを実行できます。BlueXPは通常、SaaSモデルを使用して導入されます。このモデルでは、BlueXPインターフェイスを介してサービスが有効になり、ハードウェアやソフトウェアのインストールは必要ありません。このクリックアンドランの導入モードであっても、データストアがオンプレミスとパブリッククラウドのどちらにあるかに関係なく、データ管理を実行できます。



=== BlueXPの分類には、どのようなタイプのインスタンスやVMが必要ですか？

いつ link:task-deploy-cloud-compliance.html["クラウドに導入"]：

* AWSでは、BlueXPの分類は、500GiBのgp2ディスクを含むm6i.4xlargeインスタンスで実行されます。導入時に小さいインスタンスタイプを選択できます。
* Azureでは、BlueXPの分類は、ディスクが500GiBのStandard_D16s_v3 VMで実行されます。
* GCPでは、BlueXPの分類は、500GiB Standard永続ディスクを搭載したn2-standard-16 VMで実行されます。


link:concept-cloud-compliance.html["BlueXPの分類の仕組みについて詳しくは、こちらをご覧ください"^]。



=== BlueXP分類を独自のホストに導入できますか。

はい。ネットワークまたはクラウドでインターネットにアクセスできるLinuxホストにBlueXP分類ソフトウェアをインストールできます。すべてが同じように動作し、BlueXPを使用してスキャン設定と結果を引き続き管理できます。を参照してください link:task-deploy-compliance-onprem.html["BlueXPの分類をオンプレミスに導入"] を参照してください。



=== インターネットにアクセスできないセキュアなサイトはどうでしょうか。

はい、サポートされています。可能です link:task-deploy-compliance-dark-site.html["インターネットにアクセスできないオンプレミスサイトにBlueXPを分類して導入します"] 完全にセキュアなサイトに。
