---
settings:
  name: BlueXP classification
  internal:
    pdf_enabled: true
    termcheck_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: BlueXPの分類ドキュメント
    url: "/index.html"
  - title: リリースノート
    entries:
    - title: 新機能
      url: "/whats-new.html"
    - title: 既知の制限事項
      url: "/reference-limitations.html"
  - title: 開始する
    entries:
    - title: BlueXPの分類について説明します
      url: "/concept-cloud-compliance.html"
    - title: BlueXP classificationにアクセス
      url: "/task-access.html"
    - title: BlueXP分類を導入します
      entries:
      - title: 使用する導入方法
        url: "/task-deploy-overview.html"
      - title: BlueXPを使用してクラウドに導入
        url: "/task-deploy-cloud-compliance.html"
      - title: インターネットにアクセスできるLinuxホストにインストールします
        url: "/task-deploy-compliance-onprem.html"
      - title: インターネットにアクセスできないオンプレミスのLinuxホストにインストール
        url: "/task-deploy-compliance-dark-site.html"
      - title: LinuxホストでBlueXP分類をインストールできる状態になっていることを確認します
        url: "/task-test-linux-system.html"
    - title: データソースでスキャンをアクティブ化します
      entries:
      - title: データソーススキャンの概要
        url: "/task-scanning-overview.html"
      - title: Azure NetApp Files
        url: "/task-scanning-anf.html"
      - title: Amazon FSx for ONTAP
        url: "/task-scanning-fsx.html"
      - title: Cloud Volumes ONTAP とオンプレミス ONTAP
        url: "/task-getting-started-compliance.html"
      - title: データベーススキーマ
        url: "/task-scanning-databases.html"
      - title: ファイル共有
        url: "/task-scanning-file-shares.html"
      - title: StorageGRID
        url: "/task-scanning-storagegrid.html"
    - title: Active Directory を統合します
      url: "/task-add-active-directory-datasense.html"
  - title: BlueXP分類を使用
    entries:
    - title: データのガバナンスの詳細を確認できます
      url: "/task-controlling-governance-data.html"
    - title: データのコンプライアンスの詳細を表示します
      url: "/task-controlling-private-data.html"
    - title: プライベートデータのカテゴリ
      url: "/reference-private-data-categories.html"
    - title: カスタムスキャンの作成
      url: "/task-custom-classification.html"
    - title: データを調査します
      url: "/task-investigate-data.html"
    - title: 保存した検索の作成
      url: "/task-using-policies.html"
    - title: スキャン設定を変更します
      url: "/task-managing-repo-scanning.html"
    - title: コンプライアンスレポートを生成します
      url: "/task-generating-compliance-reports.html"
  - title: BlueXPの分類を管理します
    entries:
    - title: ディレクトリをスキャン対象から除外
      url: "/task-exclude-scan-paths.html"
    - title: 既存のグループIDを「組織にオープン」として定義する
      url: "/task-add-group-id-as-open.html"
    - title: BlueXPの分類からデータソースを削除します
      url: "/task-managing-compliance.html"
    - title: BlueXPをアンインストールします
      url: "/task-uninstall-data-sense.html"
  - title: 廃止された機能
    entries:
    - title: 廃止された機能のリスト
      url: "/reference-free-paid.html"
    - title: BlueXPの分類に関する廃止措置の導入
      entries:
      - title: インターネットアクセスのない複数のホストにBlueXP分類をインストールする
        url: "/task-deploy-multi-host-install-dark-site.html"
    - title: スキャンデータの非推奨化
      entries:
      - title: Amazon S3バケットをスキャン
        url: "/task-scanning-s3.html"
      - title: OneDriveアカウントのスキャン
        url: "/task-scanning-onedrive.html"
      - title: SharePointアカウントのスキャン
        url: "/task-scanning-sharepoint.html"
      - title: Googleドライブアカウントのスキャン
        url: "/task-scanning-google-drive.html"
      - title: S3プロトコルを使用するオブジェクトストレージをスキャンする
        url: "/task-scanning-object-storage.html"
    - title: データの廃止を管理する
      entries:
      - title: ガバナンスダッシュボードでデータに関するガバナンスの詳細を表示する
        url: "/task-controlling-governance-dashboard-deprecated.html"
      - title: プライベートデータを整理します
        url: "/task-org-private-data.html"
      - title: プライベートデータを管理
        url: "/task-managing-highlights.html"
      - title: カスタムの個人データ識別子を追加します
        url: "/task-managing-data-fusion.html"
      - title: BlueXP分類操作のステータスを表示します
        url: "/task-view-compliance-actions.html"
      - title: BlueXPの分類アクションの履歴を監査します
        url: "/task-audit-data-sense-actions.html"
      - title: BlueXPの分類スキャン速度を下げます
        url: "/task-reduce-scan-speed.html"
      - title: OneDrive、SharePoint、Google Driveのアカウントを削除する
        url: "/task-managing-compliance-deprecated.html"
  - title: 参考文献
    entries:
    - title: サポートされるBlueXP分類インスタンスタイプ
      url: "/reference-instance-types.html"
    - title: データソースから収集されたメタデータ
      url: "/reference-collected-metadata.html"
    - title: BlueXP分類システムにログインする
      url: "/reference-log-in-to-instance.html"
    - title: BlueXP分類API
      url: "/api-classification.html"
  - title: 知識とサポート
    entries:
    - title: サポートに登録します
      url: "/task-support-registration.html"
    - title: ヘルプを表示します
      url: "/task-get-help.html"
  - title: よくある質問
    url: "/faq-cloud-compliance.html"
  - title: 法的通知
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
