---
settings:
  name: BlueXP classification
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: BlueXPの分類ドキュメント
    url: "/index.html"
  - title: リリースノート
    entries:
    - title: 新機能
      url: "/whats-new.html"
    - title: 既知の制限
      url: "/reference-limitations.html"
  - title: はじめに
    entries:
    - title: BlueXPの分類について説明します
      url: "/concept-cloud-compliance.html"
    - title: BlueXP分類を導入します
      entries:
      - title: BlueXPを使用してクラウドに導入
        url: "/task-deploy-cloud-compliance.html"
      - title: インターネットにアクセスできるLinuxホストにインストールします
        url: "/task-deploy-compliance-onprem.html"
      - title: インターネットにアクセスせずにオンプレミスにインストール
        url: "/task-deploy-compliance-dark-site.html"
      - title: LinuxホストでBlueXP分類をインストールできる状態になっていることを確認します
        url: "/task-test-linux-system.html"
    - title: データソースでスキャンをアクティブ化します
      entries:
      - title: Cloud Volumes ONTAP とオンプレミス ONTAP
        url: "/task-getting-started-compliance.html"
      - title: Azure NetApp Files の特長
        url: "/task-scanning-anf.html"
      - title: ONTAP 対応の Amazon FSX
        url: "/task-scanning-fsx.html"
      - title: Amazon S3 バケット
        url: "/task-scanning-s3.html"
      - title: データベーススキーマ
        url: "/task-scanning-databases.html"
      - title: OneDrive アカウント
        url: "/task-scanning-onedrive.html"
      - title: SharePoint アカウント
        url: "/task-scanning-sharepoint.html"
      - title: Googleドライブアカウント
        url: "/task-scanning-google-drive.html"
      - title: ファイル共有
        url: "/task-scanning-file-shares.html"
      - title: オブジェクトストレージ
        url: "/task-scanning-object-storage.html"
    - title: Active Directory を統合します
      url: "/task-add-active-directory-datasense.html"
    - title: ライセンスをセットアップする
      url: "/task-licensing-datasense.html"
    - title: よく寄せられる質問
      url: "/faq-cloud-compliance.html"
  - title: BlueXP分類を使用
    entries:
    - title: データのガバナンスの詳細を確認できます
      url: "/task-controlling-governance-data.html"
    - title: データのコンプライアンスの詳細を表示します
      url: "/task-controlling-private-data.html"
    - title: プライベートデータのカテゴリ
      url: "/reference-private-data-categories.html"
    - title: データを調査します
      url: "/task-investigate-data.html"
    - title: プライベートデータを整理します
      url: "/task-org-private-data.html"
    - title: データにポリシーを割り当てます
      url: "/task-using-policies.html"
    - title: プライベートデータを管理
      url: "/task-managing-highlights.html"
    - title: ファイルアクセスイベントを監視および管理します
      url: "/task-manage-file-access-events.html"
    - title: スキャン設定を変更します
      url: task-managing-repo-scanning.html
    - title: コンプライアンスレポートを生成します
      url: "/task-generating-compliance-reports.html"
  - title: BlueXPの分類を管理します
    entries:
    - title: カスタムの個人データ識別子を追加します
      url: "/task-managing-data-fusion.html"
    - title: BlueXP分類操作のステータスを表示します
      url: "/task-view-compliance-actions.html"
    - title: BlueXPの分類アクションの履歴を監査します
      url: "/task-audit-data-sense-actions.html"
    - title: BlueXPの分類スキャン速度を下げます
      url: "/task-reduce-scan-speed.html"
    - title: BlueXPの分類からデータソースを削除します
      url: "/task-managing-compliance.html"
    - title: BlueXPをアンインストールします
      url: "/task-uninstall-data-sense.html"
  - title: 参照
    entries:
    - title: サポートされるBlueXP分類インスタンスタイプ
      url: "/reference-instance-types.html"
    - title: データソースから収集されたメタデータ
      url: "/reference-collected-metadata.html"
  - title: 知識とサポート
    entries:
    - title: サポートに登録します
      url: "/task-support-registration.html"
    - title: ヘルプを表示します
      url: "/task-get-help.html"
  - title: 法的通知
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: はじめに
    links:
    - title: BlueXPの分類について説明します
      url: concept-cloud-compliance.html
    - title: 新機能
      url: whats-new.html
    - title: BlueXPを使用してBlueXP分類をクラウドに導入します
      url: task-deploy-cloud-compliance.html
    - title: インターネットを使用するLinuxホストにBlueXP分類をインストールします
      url: task-deploy-compliance-onprem.html
    - title: インターネットを使用せずに、BlueXPの分類をオンプレミスにインストール
      url: task-deploy-compliance-dark-site.html
    - title: Active Directory を統合します
      url: task-add-active-directory-datasense.html
    - title: ライセンスをセットアップする
      url: task-licensing-datasense.html
  - title: 作業環境をスキャンします
    links:
    - title: Cloud Volumes ONTAP ボリューム
      url: task-getting-started-compliance.html
    - title: オンプレミスの ONTAP ボリューム
      url: task-getting-started-compliance.html
    - title: Azure NetApp Files ボリューム
      url: task-scanning-anf.html
    - title: ONTAP ボリュームの Amazon FSX
      url: task-scanning-fsx.html
    - title: Amazon S3 バケット
      url: task-scanning-s3.html
  - title: 他のデータソースをスキャンします
    links:
    - title: 汎用の S3 バケット
      url: task-scanning-object-storage.html
    - title: ネットアップ以外のファイル共有
      url: task-scanning-file-shares.html
    - title: データベーススキーマ
      url: task-scanning-databases.html
    - title: OneDrive アカウント
      url: task-scanning-onedrive.html
    - title: SharePoint アカウント
      url: task-scanning-sharepoint.html
    - title: Googleドライブアカウント
      url: task-scanning-google-drive.html
  - title: データの詳細を表示します
    links:
    - title: プライベート情報を含むファイルを表示します
      url: task-controlling-private-data.html
    - title: ストレージに複製されているファイルを表示します
      url: task-investigate-data.html#checking-for-duplicate-files-in-your-storage-systems
    - title: データをフィルタして、特定のファイルを表示します
      url: task-investigate-data.html
    - title: 上位検索を表示するポリシーを作成します
      url: task-using-policies.html
    - title: コンプライアンスレポートを生成します
      url: task-generating-compliance-reports.html
  - title: プライベートデータを整理します
    links:
    - title: 注意が必要なファイルにタグと所有者を適用します
      url: task-org-private-data.html#applying-tags-to-manage-your-scanned-files
    - title: AIP ラベルを使用してデータを分類します
      url: task-org-private-data.html#categorizing-your-data-using-aip-labels
    - title: 独自のカスタム個人データ識別子を追加します
      url: task-managing-data-fusion.html
  - title: プライベートデータを管理
    links:
    - title: ソースファイルをコピーします
      url: task-managing-highlights.html#copying-source-files
    - title: ソースファイルを移動します
      url: task-managing-highlights.html#moving-source-files-to-an-nfs-share
    - title: ソースファイルを削除します
      url: task-managing-highlights.html#deleting-source-files
    - title: 準拠していないデータが見つかった場合にアラートを E メールで送信
      url: task-using-policies.html#sending-email-alerts-when-non-compliant-data-is-found
    - title: ファイルアクセスイベントを監視および管理します
      url: task-manage-file-access-events.html
    - title: データサブジェクトのアクセス要求に応答します
      url: task-generating-compliance-reports.html#searching-for-data-subjects-and-downloading-reports
  - title: ブログコミュニティ
    links:
    - title: ネットアップコミュニティ
      url: https://community.netapp.com/t5/BlueXP-and-Services/ct-p/CDS
    - title: BlueXPの分類のユースケース
      url: https://bluexp.netapp.com/netapp-cloud-data-sense
    - title: BlueXPブログ
      url: https://bluexp.netapp.com/blog
    - title: BlueXP Webセミナー
      url: https://bluexp.netapp.com/events
product-family:
  name: BlueXP
  repo: bluexp-family
  sidebar_label: BlueXPのすべてのマニュアル
