---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, data sense, classification, bluexp, scan shares 
summary: 既知の制限事項では、このリリースの製品ではサポートされていない機能、または正しく相互運用されない機能が特定されます。これらの制限事項をよく確認してください。 
---
= BlueXP  分類における既知の制限事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
既知の制限事項では、このリリースではサポートされていない機能や正しく相互運用されない機能が特定されます。これらの制限事項をよく確認してください。



== BlueXP分類無効オプション

2023年12月（バージョン1.26.6）リリースでは、次のオプションが削除されました。

* 監査ログ収集をアクティブ化するオプションが無効になりました。
* ディレクトリ調査中は、ディレクトリ別に個人を特定できる情報 (PII) データの数を計算するオプションは使用できません。
* Azure Information Protection（AIP）ラベルを使用してデータを統合するオプションが無効になりました。




== BlueXP分類スキャン

BlueXP 分類スキャンでは次の制限が発生します。



=== BlueXPの分類では、ボリュームの下にある共有は1つだけスキャンされます

1つのボリュームに複数のファイル共有がある場合は、最上位階層の共有がスキャンされます。たとえば、次のような共有があるとします。

* /A
* /A/B
* /C
* /D/E


この構成では、/A のデータのみがスキャンされます。/Cと /D のデータはスキャンされません。

.回避策
ボリューム内のすべての共有からデータをスキャンしていることを確認する回避策があります。次の手順を実行します。

. 作業環境で、スキャンするボリュームを追加します。
. BlueXPの分類によるボリュームのスキャンが完了したら、_Data Investigation_pageに移動し、どの共有がスキャンされているかを確認するフィルタを作成します。
+
「作業環境名」と「ディレクトリ タイプ = 共有」でデータをフィルターして、スキャンされている共有を確認します。

. ボリューム内に存在する共有の完全なリストを取得して、スキャンされていない共有を確認します。
. link:task-scanning-file-shares.html["残りの共有を共有グループに追加します"]です。
+
すべての共有を個別に追加します。例:

+
....
/C
/D
....
. 複数の共有を含む作業環境内のボリュームごとに、次の手順を実行します。




=== 最終アクセスタイムスタンプ

BlueXP分類がディレクトリのスキャンを実行すると、そのスキャンはディレクトリの**最終アクセス**フィールドに影響します。**最終アクセス**フィールドを表示すると、そのメタデータにはスキャンの日時、またはユーザーがディレクトリに最後にアクセスした日時が反映されます。
