---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, data sense, classification, scan shares 
summary: 既知の制限事項には、このリリースの製品でサポートされていない機能、またはこのリリースと正しく相互運用できない機能が記載されています。これらの制限事項を慎重に確認してください 
---
= 既知の制限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
既知の制限事項には、このリリースの製品でサポートされていない機能、またはこのリリースと正しく相互運用できない機能が記載されています。これらの制限事項を慎重に確認してください



== BlueXPの分類スキャンの制限事項



=== BlueXPの分類では、ボリュームの下にある共有は1つだけスキャンされます

1つのボリュームに複数のファイル共有がある場合は、最上位階層の共有がスキャンされます。たとえば、次のような共有があるとします。

* /A
* /A/B
* /C
* /D/E


その後、/A内のデータがスキャンされます。/Cおよび/Dのデータはスキャンされません。

.回避策
ボリューム内のすべての共有からデータをスキャンしていることを確認する回避策があります。次の手順を実行します。

. 作業環境で、スキャンするボリュームを追加します。
. BlueXPの分類によるボリュームのスキャンが完了したら、_Data Investigation_pageに移動し、どの共有がスキャンされているかを確認するフィルタを作成します。
+
「Working Environment Name」および「Directory Type = Share」でデータをフィルタリングして、どの共有がスキャンされているかを確認します。

. ボリューム内に存在する共有の完全なリストを取得して、スキャンされていない共有を確認します。
. link:task-scanning-file-shares.html["残りの共有を共有グループに追加します"]。
+
次のように、すべての共有を個別に追加する必要があります。

+
....
/C
/D
....
. 複数の共有を含む作業環境内のボリュームごとに、次の手順を実行します。

