---
sidebar: sidebar 
permalink: task-test-linux-system.html 
keywords: cloud compliance, data sense, get started, deploy cloud BlueXP classification, cloud compliance access, compliance, on-premises, linux, test linux system 
summary: LinuxホストにBlueXPの分類を手動でインストールする前に、ホストでスクリプトを実行して、BlueXPの分類をインストールするための前提条件がすべて揃っていることを確認することができます。このスクリプトは、ネットワーク内のLinuxホストまたはクラウド内のLinuxホストで実行できます。ホストはインターネットに接続することも、インターネットにアクセスできないサイトに配置することもできます。 
---
= LinuxホストでBlueXP分類をインストールできる状態になっていることを確認します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
LinuxホストにBlueXPの分類を手動でインストールする前に、ホストでスクリプトを実行して、BlueXPの分類をインストールするための前提条件がすべて揃っていることを確認することができます。このスクリプトは、ネットワーク内のLinuxホストまたはクラウド内のLinuxホストで実行できます。ホストはインターネットに接続することも、インターネットにアクセスできないサイト（「ダークサイト」）に配置することもできます。

BlueXP分類インストールスクリプトには、前提条件となるテストスクリプトも含まれています。ここで説明するスクリプトは、BlueXP分類のインストールスクリプトとは別にLinuxホストを検証するユーザ向けに設計されています。



== はじめに

次のタスクを実行します。

. BlueXPコネクタがまだインストールされていない場合は、必要に応じてインストールします。テストスクリプトはコネクタをインストールせずに実行できますが、コネクタとBlueXP分類ホストマシンの間の接続がチェックされるため、コネクタを用意することを推奨します。
. ホストマシンを準備し、すべての要件を満たしていることを確認します。
. BlueXP分類ホストマシンからのアウトバウンドインターネットアクセスを有効にします。
. すべてのシステムで必要なすべてのポートが有効になっていることを確認します。
. 前提条件テストスクリプトをダウンロードして実行します。




== コネクタを作成します

BlueXPをインストールして使用するには、BlueXPコネクタが必要です。ただし、コネクタを使用せずに前提条件スクリプトを実行することはできます。

可能です https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-on-prem.html["コネクタをオンプレミスにインストールします"^] ネットワーク内のLinuxホストまたはクラウド内のLinuxホスト。BlueXP分類をオンプレミスにインストールすることを計画している一部のユーザは、コネクタをオンプレミスにインストールすることもできます。

クラウドプロバイダ環境でコネクタを作成するには、を参照してください https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-aws.html["AWS でコネクタを作成する"^]、 https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-azure.html["Azure でコネクタを作成する"^]または https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-google.html["GCP でコネクタを作成する"^]。

前提条件スクリプトを実行するときに、コネクタシステムのIPアドレスまたはホスト名が必要になります。この情報は、コネクタをオンプレミスにインストールした場合に表示されます。コネクタがクラウドに導入されている場合は、BlueXPコンソールで[ヘルプ]アイコンをクリックし、[*サポート]を選択して、[* BlueXPコネクタ*]をクリックします。



== ホストの要件を確認

BlueXP分類ソフトウェアは、特定のオペレーティングシステム要件、RAM要件、ソフトウェア要件などを満たすホストで実行する必要があります。

* BlueXPの分類は、他のアプリケーションと共有するホストではサポートされません。専用のホストである必要があります。
* オンプレミスでホストシステムを構築する場合は、BlueXP分類スキャンを実行するデータセットのサイズに応じて、3つのシステムサイズの中から選択できます。
+
[cols="18,18,26,30"]
|===
| システムサイズ | CPU | RAM（スワップメモリを無効にする必要があります） | ディスク 


| *大きい* | 16 CPU | 64GBのRAM | 500GiB SSDオン/、または
-100GiBは/optで利用可能
-395GiBは/var/lib/dockerで使用可能
-5GiB（/tmp 


| *中* | 8 CPU | 32GBのRAM | 200GiB SSDオン/、または
-50GiBは/optで利用可能
-145GiBは/var/lib/dockerで使用可能
-5GiB（/tmp 


| *小さい* | 8 CPU | 16GB の RAM | 100GiB SSDオン/、または
-50GiBは/optで利用可能
-45GiBは/var/lib/dockerで使用可能
-5GiB（/tmp 
|===
+
これらの小さいシステムを使用する場合は制限があることに注意してください。を参照してください link:concept-cloud-compliance.html#using-a-smaller-instance-type["小さいインスタンスタイプを使用しています"] を参照してください。

* BlueXP分類インストール用にコンピューティングインスタンスをクラウドに導入する場合は、上記の「大規模」システム要件を満たすシステムを推奨します。
+
** * AWS EC2インスタンスタイプ*：「m6i.4xlarge」を推奨します。 link:reference-instance-types.html#aws-instance-types["その他のAWSインスタンスタイプを参照してください"^]。
** * Azure VMのサイズ*：「Standard_D16s_v3」を推奨します。 link:reference-instance-types.html#azure-instance-types["その他のAzureインスタンスタイプを参照してください"^]。
** *GCPマシンタイプ*:「n2-standard-16」をお勧めします。 link:reference-instance-types.html#gcp-instance-types["追加のGCPインスタンスタイプを参照してください"^]。


* * UNIXフォルダ権限*：次の最小UNIX権限が必要です。
+
[cols="25,25"]
|===
| フォルダ | 最小権限 


| /tmp | `rwxrwxrwt` 


| /opt | `rwxr-xr-x` 


| /var/lib/dockerを使用します | `rwx------` 


| /user/lib/systemd/system | `rwxr-xr-x` 
|===
* * オペレーティング・システム * ：
+
** 次のオペレーティングシステムでは、Dockerコンテナエンジンを使用する必要があります。
+
*** Red Hat Enterprise Linuxバージョン7.8および7.9 - Linuxカーネルのバージョンは4.0以降である必要があります。
*** CentOSバージョン7.8および7.9 - Linuxカーネルのバージョンは4.0以上である必要があります。
*** Ubuntu 22.04（BlueXP分類バージョン1.23以降が必要）






* * Red Hat Subscription Management *：ホストはRed Hat Subscription Managementに登録されている必要があります。登録されていない場合、システムはインストール時に必要なサードパーティ製ソフトウェアを更新するためのリポジトリにアクセスできません。
* *その他のソフトウェア*：BlueXP分類をインストールする前に、次のソフトウェアをホストにインストールする必要があります。
+
** 使用しているOSに応じて、次のいずれかのコンテナエンジンをインストールする必要があります。
+
*** Docker Engineバージョン19.3.1以降。 https://docs.docker.com/engine/install/["インストール手順を確認します"^]。
+
https://youtu.be/Ogoufel1q6c["こちらのビデオをご覧ください"^] では、CentOSへのDockerのインストールの簡単なデモをご覧ください。



** Pythonバージョン3.6以降。 https://www.python.org/downloads/["インストール手順を確認します"^]。


* *ファイアウォールの考慮事項*:使用を計画している場合 `firewalld`は、BlueXP分類をインストールする前に有効にすることを推奨します。次のコマンドを実行して設定します `firewalld` BlueXPと互換性があることを確認します。
+
....
firewall-cmd --permanent --add-service=http
firewall-cmd --permanent --add-service=https
firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --permanent --add-port=8080/tcp
firewall-cmd --permanent --add-port=443/tcp
firewall-cmd --reload
....
+
BlueXP分類ホストを（分散モデルで）スキャナノードとして使用する場合は、この時点でプライマリシステムに次のルールを追加します。

+
....
firewall-cmd --permanent --add-port=2377/tcp
firewall-cmd --permanent --add-port=7946/udp
firewall-cmd --permanent --add-port=7946/tcp
firewall-cmd --permanent --add-port=4789/udp
....
+
を有効または更新するたびに、Dockerを再起動する必要があります `firewalld` 設定：





== BlueXPの分類からアウトバウンドのインターネットアクセスを有効にします

BlueXPの分類にはアウトバウンドのインターネットアクセスが必要です。仮想ネットワークまたは物理ネットワークでインターネットアクセスにプロキシサーバを使用している場合は、次のエンドポイントに接続するためのアウトバウンドのインターネットアクセスがBlueXP分類インスタンスにあることを確認してください。


TIP: このセクションは、インターネットに接続されていないサイトにインストールされているホストシステムには必要ありません。

[cols="43,57"]
|===
| エンドポイント | 目的 


| \ https://api.bluexp.netapp.com | ネットアップアカウントを含むBlueXPサービスとの通信 


| ¥ https://netapp-cloud-account.auth0.com ¥ https://auth0.com | BlueXP Webサイトとの通信により、ユーザ認証を一元化。 


| https://support.compliance.api.bluexp.netapp.com/\ https://hub.docker.com \ https://auth.docker.io \ https://registry-1.docker.io \ https://index.docker.io/\ https://dseasb33srnrn.cloudfront.net/\ https://production.cloudflare.docker.com/ | ソフトウェアイメージ、マニフェスト、テンプレートへのアクセス、およびログとメトリックの送信を提供します。 


| \ https://support.compliance.api.bluexp.netapp.com/ | ネットアップが監査レコードからデータをストリーミングできるようにします。 


| https://github.com/docker https://download.docker.com | Dockerのインストールに必要なパッケージを提供します。 


| http://mirror.centos.org http://mirrorlist.centos.org http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.107-3.el7.noarch.rpm | CentOSのインストールに必要なパッケージを提供します。 


| \http://packages.ubuntu.com/
\http://archive.ubuntu.com | Ubuntuのインストールに必要なパッケージを提供します。 
|===


== 必要なすべてのポートが有効になっていることを確認します

コネクタ、BlueXP分類、Active Directory、データソースの間の通信に必要なすべてのポートが開いていることを確認する必要があります。

[cols="25,25,50"]
|===
| 接続タイプ | ポート | 説明 


| コネクタ<> BlueXPの分類 | 8080（TCP）、443（TCP）、および80 | コネクタのファイアウォールルールまたはルーティングルールで、ポート443を介したBlueXP分類インスタンスとの間のインバウンドおよびアウトバウンドトラフィックを許可する必要があります。ポート8080が開いていることを確認し、BlueXPでインストールの進行状況を確認します。 


| Connector <> ONTAP cluster（NAS） | 443（TCP）  a| 
BlueXPはHTTPSを使用してONTAP クラスタを検出しましたカスタムファイアウォールポリシーを使用する場合は、コネクタホストでポート443経由のアウトバウンドHTTPSアクセスを許可する必要があります。コネクタがクラウド内にある場合、すべてのアウトバウンド通信は、事前定義されたファイアウォールまたはルーティングルールによって許可されます。

|===


== BlueXPの分類の前提条件スクリプトを実行します

BlueXPの分類の前提条件スクリプトを実行するには、次の手順を実行します。

https://youtu.be/_RCYpuLXiV0?si=QLGUw8mqPrz9qs4B["こちらのビデオをご覧ください"^] 前提条件スクリプトの実行方法と結果の解釈方法を確認します。

.必要なもの
* Linux システムがを満たしていることを確認します <<ホストの要件を確認,ホストの要件>>。
* システムに前提条件となる2つのソフトウェアパッケージ（Docker EngineとPython 3）がインストールされていることを確認します。
* Linux システムに対する root 権限があることを確認してください。


.手順
. からBlueXPの分類のPrerequisitesスクリプトをダウンロードします https://mysupport.netapp.com/site/products/all/details/cloud-data-sense/downloads-tab/["ネットアップサポートサイト"^]。選択するファイルの名前は* standalone-pre-requisite-tester-tester*<version> です。
. 使用するLinuxホストにファイルをコピーします（を使用） `scp` またはその他の方法を使用してください）。
. スクリプトを実行する権限を割り当てます。
+
[source, cli]
----
chmod +x standalone-pre-requisite-tester-v1.25.0
----
. 次のコマンドを使用してスクリプトを実行します。
+
[source, cli]
----
 ./standalone-pre-requisite-tester-v1.25.0 <--darksite>
----
+
インターネットにアクセスできないホストでスクリプトを実行する場合にのみ、「--darksite」オプションを追加します。ホストがインターネットに接続されていない場合、一部の前提条件テストがスキップされます。

. BlueXP分類ホストマシンのIPアドレスの入力を求められます。
+
** IPアドレスまたはホスト名を入力します。


. BlueXP Connectorがインストールされているかどうかを確認するメッセージが表示されます。
+
** コネクタが取り付けられていない場合は、「* N *」と入力します。
** コネクタが取り付けられている場合は、「* Y *」と入力します。をクリックし、テストスクリプトで接続をテストできるように、BlueXPコネクタのIPアドレスまたはホスト名を入力します。


. このスクリプトでは、システムに対してさまざまなテストが実行され、処理が進むにつれて結果が表示されます。終了すると、セッションのログがという名前のファイルに書き込まれます `prerequisites-test-<timestamp>.log` をクリックします `/opt/netapp/install_logs`。


.結果
すべての前提条件テストが正常に実行されたら、準備ができたらBlueXP分類をホストにインストールできます。

問題が検出された場合は、「推奨」または「必須」に分類され、修正が必要です。通常、推奨される問題は、BlueXPの分類のスキャンとカテゴリ化のタスクの実行に時間がかかる原因となる項目です。これらの項目は修正する必要はありませんが、対処する必要があります。

「必須」の問題がある場合は、問題を修正してから、前提条件テストスクリプトを再度実行する必要があります。
