---
sidebar: sidebar 
permalink: task-test-linux-system.html 
keywords: cloud compliance, data sense, get started, deploy cloud data sense, cloud compliance access, compliance, on-premises, linux, test linux system 
summary: LinuxホストにData Senseを手動でインストールする前に、ホストでスクリプトを実行して、Data Senseをインストールするための前提条件がすべて揃っていることを確認できます。このスクリプトは、ネットワーク内のLinuxホストまたはクラウド内のLinuxホストで実行できます。ホストはインターネットに接続することも、インターネットにアクセスできないサイトに配置することもできます。 
---
= LinuxホストでData Senseをインストールできる状態になっていることを確認します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
LinuxホストにData Senseを手動でインストールする前に、ホストでスクリプトを実行して、Data Senseをインストールするための前提条件がすべて揃っていることを確認できます。このスクリプトは、ネットワーク内のLinuxホストまたはクラウド内のLinuxホストで実行できます。ホストはインターネットに接続することも、インターネットにアクセスできないサイト（「ダークサイト」）に配置することもできます。

Data Senseインストールスクリプトには、前提条件となるテストスクリプトも含まれています。ここで説明するスクリプトは、Data Senseインストールスクリプトとは別にLinuxホストを検証するユーザ向けに設計されています。



== はじめに

次のタスクを実行します。

. BlueXPコネクタがまだインストールされていない場合は、必要に応じてインストールします。コネクタをインストールせずにテストスクリプトを実行できますが、コネクタとData Senseホストマシン間の接続がチェックされるため、コネクタを用意することをお勧めします。
. ホストマシンを準備し、すべての要件を満たしていることを確認します。
. Data Senseホストマシンからのアウトバウンドインターネットアクセスを有効にします。
. すべてのシステムで必要なすべてのポートが有効になっていることを確認します。
. 前提条件テストスクリプトをダウンロードして実行します。




== コネクタを作成します

データセンスをインストールして使用するには、BlueXPコネクタが必要です。ただし、コネクタを使用せずに前提条件スクリプトを実行することはできます。

可能です https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-connector-on-prem.html["コネクタをオンプレミスにインストールします"^] ネットワーク内のLinuxホストまたはクラウド内のLinuxホスト。データセンスをオンプレミスにインストールする予定のユーザによっては、 Connector をオンプレミスにインストールすることもできます。

クラウドプロバイダ環境でコネクタを作成するには、を参照してください https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-connector-aws.html["AWS でコネクタを作成する"^]、 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-connector-azure.html["Azure でコネクタを作成する"^]または https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-connector-google.html["GCP でコネクタを作成する"^]。

前提条件スクリプトを実行するときに、コネクタシステムのIPアドレスまたはホスト名が必要になります。この情報は、コネクタをオンプレミスにインストールした場合に表示されます。コネクタがクラウドに導入されている場合は、BlueXPコンソールで[ヘルプ]アイコンをクリックし、[*サポート]を選択して、[* BlueXPコネクタ*]をクリックします。



== ホストの要件を確認

データセンスソフトウェアは、特定のオペレーティングシステム要件、 RAM 要件、ソフトウェア要件などを満たすホストで実行する必要があります。

* データセンスは、他のアプリケーションと共有されるホストではサポートされません。ホストは専用のホストである必要があります。


* オンプレミスでホストシステムを構築する場合は、Data Senseスキャンを実行するデータセットのサイズに応じて、3つのシステムサイズから選択できます。
+
[cols="18,18,26,30"]
|===
| システムサイズ | CPU | RAM（スワップメモリを無効にする必要があります） | ディスク 


| *大きい* | 16 CPU | 64GBのRAM | 500GiB SSDオン/または-100GiBオン/opt-395GiBオン/var-5GiBオン/tmp 


| *中* | 8 CPU | 32GBのRAM | SSDが200GiB、または-50GiBが/opt-145GiBが/var-5GiBが/tmpにある 


| *小さい* | 8 CPU | 16GB の RAM | 100GiB SSDオン/または-50GiBオン/opt-45GiBオン/var-5GiBオン/tmp 
|===
+
これらの小さいシステムを使用する場合は制限があることに注意してください。を参照してください link:concept-cloud-compliance.html#using-a-smaller-instance-type["小さいインスタンスタイプを使用しています"] を参照してください。

* Data Senseインストール用にクラウドインスタンスを導入する場合は、上記の「大規模」システム要件を満たすシステムを推奨します。
+
** * AWS EC2インスタンスタイプ*：「m6i.4xlarge」を推奨します。 link:reference-instance-types.html#aws-instance-types["その他のAWSインスタンスタイプを参照してください"^]。
** * Azure VMのサイズ*：「Standard_D16s_v3」を推奨します。 link:reference-instance-types.html#azure-instance-types["その他のAzureインスタンスタイプを参照してください"^]。
** *GCPマシンタイプ*:「n2-standard-16」をお勧めします。 link:reference-instance-types.html#gcp-instance-types["追加のGCPインスタンスタイプを参照してください"^]。


* *オペレーティング・システム*：Red Hat Enterprise LinuxまたはCentOSバージョン8.0~8.7
+
** CentOS Stream 8もサポートされています
** バージョン7.8または7.9を使用できますが、Linuxカーネルバージョンは4.0以降である必要があります
** OSにDockerエンジンがインストールされている必要があります


* * Red Hat Subscription Management *：Red Hat Enterprise LinuxシステムをRed Hat Subscription Managementに登録する必要があります。登録されていないと、インストール時に必要なサードパーティ製ソフトウェアを更新するためのリポジトリにアクセスできません。
* *追加ソフトウェア*：Data Senseをインストールする前に、次のソフトウェアをホストにインストールする必要があります。
+
** Docker Engineバージョン19.3.1以降。 https://docs.docker.com/engine/install/["インストール手順を確認します"^]。
** Python 3 バージョン 3.6 以降。 https://www.python.org/downloads/["インストール手順を確認します"^]。


* *ファイアウォールの考慮事項*:使用を計画している場合 `firewalld`では、データセンスをインストールする前に有効にすることをお勧めします。次のコマンドを実行して設定します `firewalld` データセンスとの互換性を確保するために、次のようにします。
+
....
firewall-cmd --permanent --add-service=http
firewall-cmd --permanent --add-service=https
firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --permanent --add-port=8080/tcp
firewall-cmd --permanent --add-port=443/tcp
firewall-cmd --reload
....
+
（分散モデルで）スキャナノードとして追加のData Senseホストを使用する場合は、この時点でプライマリシステムに次のルールを追加します。

+
....
firewall-cmd --permanent --add-port=2377/tcp
firewall-cmd --permanent --add-port=7946/udp
firewall-cmd --permanent --add-port=7946/tcp
firewall-cmd --permanent --add-port=4789/udp
....
+
を有効にした場合 `firewalld` Data Senseをインストールしたら、Dockerを再起動する必要があります。





== Data Senseからのアウトバウンドインターネットアクセスを有効にします

Data Senseにはアウトバウンドのインターネットアクセスが必要です。仮想ネットワークまたは物理ネットワークでインターネットアクセスにプロキシサーバを使用している場合は、 Data sense インスタンスにアウトバウンドのインターネットアクセスがあり、次のエンドポイントに接続できることを確認します。

ヒント:: このセクションは、インターネットに接続されていないサイトにインストールされているホストシステムには必要ありません。


[cols="43,57"]
|===
| エンドポイント | 目的 


| \ https://api.bluexp.netapp.com | ネットアップアカウントを含むBlueXPサービスとの通信 


| ¥ https://netapp-cloud-account.auth0.com ¥ https://auth0.com | BlueXP Webサイトとの通信により、ユーザ認証を一元化。 


| https://support.compliance.api.bluexp.netapp.com/\ https://hub.docker.com \ https://auth.docker.io \ https://registry-1.docker.io \ https://index.docker.io/\ https://dseasb33srnrn.cloudfront.net/\ https://production.cloudflare.docker.com/ | ソフトウェアイメージ、マニフェスト、テンプレートへのアクセス、およびログとメトリックの送信を提供します。 


| \ https://support.compliance.api.bluexp.netapp.com/ | ネットアップが監査レコードからデータをストリーミングできるようにします。 


| ¥ https://github.com/docker ¥ https://download.docker.com ¥ http://mirror.centos.org ¥ http://mirrorlist.centos.org ¥ http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.107-3.el7.noarch.rpm | インストールの前提条件パッケージを提供します。 
|===


== 必要なすべてのポートが有効になっていることを確認します

コネクタ、データセンス、Active Directory、およびデータソース間の通信に必要なすべてのポートが開いていることを確認する必要があります。

[cols="25,25,50"]
|===
| 接続タイプ | ポート | 説明 


| コネクタ<>データ検出 | 8080（TCP）、443（TCP）、および80 | コネクタのファイアウォールまたはルーティングルールで、ポート443からデータセンスインスタンスへのインバウンドおよびアウトバウンドトラフィックを許可する必要があります。ポート8080が開いていることを確認し、BlueXPでインストールの進行状況を確認します。 


| Connector <> ONTAP cluster（NAS） | 443（TCP）  a| 
BlueXPはHTTPSを使用してONTAP クラスタを検出しましたカスタムファイアウォールポリシーを使用する場合は、コネクタホストでポート443経由のアウトバウンドHTTPSアクセスを許可する必要があります。コネクタがクラウド内にある場合、すべてのアウトバウンド通信は、事前定義されたファイアウォールまたはルーティングルールによって許可されます。

|===


== Data Sense Prerequisitesスクリプトを実行します

Data Sense Prerequisitesスクリプトを実行するには、次の手順を実行します。

.必要なもの
* Linux システムがを満たしていることを確認します <<ホストの要件を確認,ホストの要件>>。
* システムに、前提条件となる2つのソフトウェアパッケージ（Docker EngineとPython 3）がインストールされていることを確認します。
* Linux システムに対する root 権限があることを確認してください。


.手順
. からData Sense Prerequisitesスクリプトをダウンロードします https://mysupport.netapp.com/site/products/all/details/cloud-data-sense/downloads-tab/["ネットアップサポートサイト"^]。選択するファイルの名前は* standalone-pre-requisite-tester-tester*<version> です。
. 使用するLinuxホストにファイルをコピーします（を使用） `scp` またはその他の方法を使用してください）。
. スクリプトを実行する権限を割り当てます。
+
[source, cli]
----
chmod +x standalone-pre-requisite-tester-v1.21.0
----
. 次のコマンドを使用してスクリプトを実行します。
+
[source, cli]
----
 ./standalone-pre-requisite-tester-v1.21.0 <--darksite>
----
+
インターネットにアクセスできないホストでスクリプトを実行する場合にのみ、「--darksite」オプションを追加します。ホストがインターネットに接続されていない場合、一部の前提条件テストがスキップされます。

. Data SenseホストマシンのIPアドレスの入力を求めるプロンプトが表示されます。
+
** IPアドレスまたはホスト名を入力します。


. BlueXP Connectorがインストールされているかどうかを確認するメッセージが表示されます。
+
** コネクタが取り付けられていない場合は、「* N *」と入力します。
** コネクタが取り付けられている場合は、「* Y *」と入力します。をクリックし、テストスクリプトで接続をテストできるように、BlueXPコネクタのIPアドレスまたはホスト名を入力します。


. このスクリプトでは、システムに対してさまざまなテストが実行され、処理が進むにつれて結果が表示されます。終了すると、セッションのログがという名前のファイルに書き込まれます `prerequisites-test-<timestamp>.log` をクリックします `/opt/netapp/install_logs`。


.結果
すべての前提条件テストが正常に実行された場合は、準備ができたらData Senseをホストにインストールできます。

問題が検出された場合は、「推奨」または「必須」に分類され、修正が必要です。推奨される問題は、通常、Data Senseのスキャンおよび分類タスクの実行速度が遅くなる項目です。これらの項目は修正する必要はありませんが、対処する必要があります。

「必須」の問題がある場合は、問題を修正してから、前提条件テストスクリプトを再度実行する必要があります。
