---
sidebar: sidebar 
permalink: task-audit-data-sense-actions.html 
keywords: compliance, actions, view progress, audit, logs, installation 
summary: BlueXPの分類では、BlueXPの分類でスキャンするすべての作業環境とデータソースのファイルに対して実行された管理アクティビティがログに記録されます。BlueXPの分類では、BlueXP分類インスタンスを導入する際のアクティビティも記録されます。 
---
= BlueXPの分類アクションの履歴の監査
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPの分類では、BlueXPの分類でスキャンするすべての作業環境とデータソースのファイルに対して実行された管理アクティビティがログに記録されます。BlueXPの分類では、BlueXP分類インスタンスを導入する際のアクティビティも記録されます。

BlueXP分類監査ログファイルの内容を表示したり、ファイルをダウンロードして、どのファイルが変更されたか、いつ変更されたかを確認したりできます。たとえば、発行された要求、要求の時刻、ファイルが削除された場合のソースの場所、ファイルが移動された場合のソースとデスティネーションの場所などの詳細を確認できます。



== ログファイルの内容

監査ログの各行には、次の形式で情報が表示されます。

`<full date> | <status> | ds_audit_logger | <module> | 0 | 0 | File <full file path> deleted from device <device path> - <result>`

* 日付と時刻-イベントの完全なタイムスタンプ
* Status -情報、警告
* アクションタイプ（削除、コピー、移動、ポリシーの作成、ポリシーの更新、 ファイルの再スキャン、JSONレポートのダウンロードなど）
* ファイル名（ファイルに関連するアクションの場合）
* アクションの詳細-何が行われたか：アクションによって異なります
+
** ポリシー名
** 移動元と移動先のデータ用
** コピー元およびコピー先の場合
** tag-tag nameを指定します
** をクリックします
** Eメールアラートの場合- Eメールアドレス/アカウント




たとえば、ログファイルの次の行は、コピー処理が成功し、コピー処理が失敗した場合を示しています。

....
2022-06-06 15:23:08,910 | INFO | ds_audit_logger | es_scanned_file | 237 | 49 | Copy file /CIFS_share/data/dop1/random_positives.tsv from device 10.31.133.183 (type: SMB_SHARE) to device 10.31.130.133:/export_reports (NFS_SHARE) - SUCCESS
2022-06-06 15:23:08,968 | WARNING | ds_audit_logger | es_scanned_file | 239 | 153 | Copy file /CIFS_share/data/compliance-netapp.tar.gz from device 10.31.133.183 (type: SMB_SHARE) to device 10.31.130.133:/export_reports (NFS_SHARE) - FAILURE
....


== ログファイルにアクセスします

管理監査ログファイルは、BlueXP分類マシンの次の場所にあります。 `/opt/netapp/audit_logs/`

インストール監査ログファイルがに書き込まれます `/opt/netapp/install_logs/`

各ログファイルのサイズは最大で10MBです。この制限に達すると、新しいログファイルが開始されます。ログファイルの名前は「DataSense _ audit.log」、「DataSense _ audit.log.1」、「DataSense _ audit.log.2」などです。最大数の100個のログファイルがシステムの古いログファイルに保持されている場合、最大数に達すると自動的に削除されます。

BlueXP分類がオンプレミスのLinuxマシンまたはクラウドに導入したLinuxマシンにインストールされている場合は、ログファイルに直接移動できます。

BlueXP分類をクラウドに導入する場合は、BlueXP分類インスタンスにSSHで接続する必要があります。システムにSSHするには、ユーザとパスワードを入力するか、BlueXPコネクタのインストール時に入力したSSHキーを使用します。SSHコマンドは次のとおりです。

 ssh -i <path_to_the_ssh_key> <machine_user>@<datasense_ip>
* <path-to_The _ssh_key>= SSH認証キーの場所
* <machine_user>：
+
** AWSの場合：<ec2-user>を使用します
** Azureの場合：BlueXPインスタンス用に作成したユーザを使用します
** GCPの場合：BlueXPインスタンス用に作成されたユーザーを使用します


* <datasension_IP>=仮想マシンインスタンスのIPアドレス


クラウドのシステムにアクセスするには、セキュリティグループのインバウンドルールを変更する必要があります。詳細については、以下を参照してください。

* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-ports-aws.html["AWSのセキュリティグループのルール"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-ports-azure.html["Azureのセキュリティグループルール"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-ports-gcp.html["Google Cloudのファイアウォールルール"^]

