---
sidebar: sidebar 
permalink: task-add-group-id-as-open.html 
keywords: permissions, open to organization, file access 
summary: NFSファイル共有内のファイルまたはフォルダにグループIDが添付されている場合、グループIDはファイルまたはフォルダに対する権限（組織に対して開かれているかどうかなど）を定義します。一部のグループID（GID）に「組織を開く」権限レベルが設定されていない場合は、その権限をGIDに追加して、そのGIDが添付されているファイルやフォルダが「組織に対して開かれている」とみなされるようにすることができます。 
---
= BlueXP  分類で組織にオープンとして追加のグループIDを定義する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
グループID（GID）がNFSファイル共有内のファイルまたはフォルダに添付される場合、グループIDはファイルまたはフォルダに対する権限（組織に対して開かれているかどうかなど）を定義します。一部のグループID（GID）に「組織を開く」権限レベルが設定されていない場合は、その権限をGIDに追加して、そのGIDが添付されているファイルやフォルダが「組織に対して開かれている」とみなされるようにすることができます。

この変更を行ってBlueXPの分類でファイルやフォルダが再スキャンされると、これらのグループIDが関連付けられているファイルやフォルダには、[調査の詳細]ページにこの権限が表示され、ファイルの権限を表示しているレポートにも表示されます。

この機能をアクティブ化するには、構成ファイルを編集してスクリプトを実行できるように、BlueXP分類システムにログインする必要があります。ソフトウェアを手動でLinuxマシンにインストールしたか、インスタンスをクラウドに導入したかに応じて、の方法を参照してください。link:reference-log-in-to-instance.html["BlueXP分類システムにログインする"]



== 「組織に開く」権限をグループIDに追加する

このタスクを開始する前に、グループID番号（GID）が必要です。

.手順
. BlueXP  分類システムで、「/opt/ NetApp /config/custom_configuration」に移動してファイルを開きます `data_provider.yaml`。
. 「organization_group_ids:[]」行にグループIDを追加します。例：
+
 organization_group_ids: [1014, 1015, 21, 2021, 1013, 2020, 1018, 1019]
+
このファイルの他の内容は変更しないでください。

. 変更をファイルに保存します。
. 「/opt/netapp/Datasense/tools/customer _configuration/data_providers」に移動し、次のスクリプトを実行します。
+
 update_data_providers_from_config_file.sh
+
このコマンドは、変更されたグループID権限を分類エンジンにコミットします。



.結果
その後のデータスキャンでは、これらのグループIDが「組織に対して開かれている」と添付されているファイルまたはフォルダが特定されます。

次の手順を使用して、グループIDのリストを編集したり、過去に追加したグループIDを削除したりできます。変更したグループIDのリストは、スクリプトを実行して変更をコミットすると更新されます。



== 現在のグループIDのリストを表示する

設定ファイルの内容が、スクリプトの実行後に実際にコミットされた内容と異なる `update_data_providers_from_config_file.sh`可能性があり `data_provider.yaml`ます。BlueXPの分類に追加したグループIDの現在のリストを表示するには、「/opt/netapp/Datasense/tools/customer _configuration/data_providers」から次のコマンドを実行します。

 get_data_providers_configuration.sh