---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense' 
summary: BlueXPの新機能をご紹介します。 
---
= BlueXP分類の新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPの新機能をご紹介します。



== 2023年4月3日（バージョン1.22）



=== 新しいデータ検出評価レポート

Data Discovery Assessment Reportでは、スキャンされた環境の概要を分析して、システムの調査結果を強調し、懸念領域と潜在的な修復手順を示します。このレポートの目的は、データガバナンスの懸念、データセキュリティの危険性、データセットのデータコンプライアンスギャップに対する認識を高めることです。 https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html#data-discovery-assessment-report["Data Discovery Assessment Reportを生成して使用する方法を説明します"]。



=== クラウド内の小規模インスタンスにBlueXPの分類機能を導入できます

AWS環境のBlueXP ConnectorからBlueXPの分類を導入する際に、デフォルトのインスタンスよりも小さい2つのインスタンスタイプから選択できるようになりました。小規模な環境をスキャンする場合は、クラウドコストを節約できます。ただし、小さいインスタンスを使用する場合はいくつかの制限があります。 https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html#using-a-smaller-instance-type["使用可能なインスタンスタイプと制限事項を参照してください"]。



=== BlueXPの分類をインストールする前に、スタンドアロンスクリプトを使用してLinuxシステムを認定できるようになりました

BlueXP分類インストールとは別に、Linuxシステムがすべての前提条件を満たしていることを確認する場合は、前提条件のみをテストするスクリプトをダウンロードできます。 https://docs.netapp.com/us-en/bluexp-classification/task-test-linux-system.html["LinuxホストでBlueXPのインストール準備が完了しているかどうかを確認する方法を説明します"]。



== 2023年3月7日（バージョン1.21）



=== BlueXPの分類UIから独自のカスタムカテゴリを追加する新機能

BlueXPの分類で独自のカスタムカテゴリを追加できるようになりました。これにより、それらのカテゴリに該当するファイルがBlueXPの分類で識別されます。BlueXPには多くの種類があります https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-categories["事前定義されたカテゴリ"]そのため、この機能を使用すると、カスタムカテゴリを追加して、組織固有の情報がデータ内のどこにあるかを特定できます。

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-categories["詳細はこちら。"^]。



=== BlueXPの分類UIからカスタムキーワードを追加できるようになりました

BlueXPの分類では、今後のスキャンでBlueXPの分類によって特定されるカスタムキーワードを追加できます。ただし、BlueXP分類Linuxホストにログインし、コマンドラインインターフェイスを使用してキーワードを追加する必要がありました。今回のリリースでは、BlueXPの分類UIでカスタムキーワードを追加できるようになり、キーワードの追加や編集が非常に簡単になりました。

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-keywords-from-a-list-of-words["BlueXPの分類UIからカスタムキーワードを追加する方法については、こちらをご覧ください"^]。



=== 「最終アクセス時間」が変更されるときに、BlueXPの分類*がファイルをスキャンすることはできません

デフォルトでは、BlueXPの分類に適切な「書き込み」権限がないと、BlueXPの分類では「最終アクセス時間」を元のタイムスタンプに戻すことができないため、ボリューム内のファイルはスキャンされません。ただし、最終アクセス時刻がファイルの元の時刻にリセットされていてもかまわない場合は、[設定]ページでこの動作を無効にして、権限に関係なくBlueXPの分類でボリュームがスキャンされるようにすることができます。

この機能と併せて、「Scan Analysis Event」という新しいフィルタが追加され、BlueXPの分類で最終アクセス時刻を元に戻すことができなかったために分類されなかったファイルや、BlueXPの分類で最終アクセス時刻を元に戻すことができなかったにもかかわらず分類されたファイルを表示できるようになりました。

https://docs.netapp.com/us-en/bluexp-classification/reference-collected-metadata.html#last-access-time-timestamp["「最終アクセス時間のタイムスタンプ」とBlueXPの分類に必要な権限について詳しくは、こちらをご覧ください"]。



=== BlueXPは、3つの新しいタイプの個人データを分類しています

BlueXPの分類では、次のタイプのデータを含むファイルを特定して分類できます。

* ボツワナIDカード（Omang）番号
* ボツワナパスポート番号
* シンガポール国民登録IDカード（NRIC）


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["BlueXPの分類によってデータから特定できるすべてのタイプの個人データを確認できます"]。



=== ディレクトリの機能が更新されました

* データ調査レポートの[Light CSV Report]オプションに、ディレクトリからの情報が含まれるようになりました。
* [Last Accessed]時間フィルタに、ファイルとディレクトリの両方の最終アクセス時刻が表示されるようになりました。




=== インストールの機能拡張

* BlueXPの分類は、CentOS Stream 8を実行しているLinuxホストにインストールできます。
* インターネットアクセスがないサイト（ダークサイト）用のBlueXP分類インストーラで、インストールを成功させるためにシステムとネットワークの要件が満たされていることを確認するための事前チェックが実行されるようになりました。
* インストール監査ログファイルは保存され、に書き込まれます `/ops/netapp/install_logs`。




== 2023年2月5日（バージョン1.20）



=== 任意のEメールアドレスにポリシーベースの通知Eメールを送信できます

以前のバージョンのBlueXP分類では、特定のクリティカルポリシーが結果を返したときに、アカウントのBlueXPユーザにEメールアラートを送信できました。この機能を使用すると、オンラインでないときにデータを保護するための通知を受け取ることができます。また、ポリシーから、BlueXPアカウントに登録されていない最大20個の電子メールアドレスを持つ他のユーザーに電子メールアラートを送信することもできます。

https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html#sending-email-alerts-when-non-compliant-data-is-found["ポリシーの結果に基づいて電子メールアラートを送信する方法については、こちらをご覧ください"]。



=== BlueXPの分類UIから個人用パターンを追加できるようになりました

BlueXPの分類では、カスタムの「個人データ」を追加できるようになりました。BlueXPの分類で今後のスキャンで特定できるようになります。ただし、BlueXP分類Linuxホストにログインし、コマンドラインを使用してカスタムパターンを追加する必要がありました。このリリースでは、BlueXPの分類UIで正規表現を使用して個人用パターンを追加できるようになり、カスタムパターンの追加と編集が非常に簡単になりました。

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-personal-data-identifiers-using-a-regex["BlueXPの分類UIからカスタムパターンを追加する方法については、こちらをご覧ください"^]。



=== BlueXPの分類を使用して1、500万個のファイルを移動できます

これまで、BlueXPの分類では、最大100、000個のソースファイルを任意のNFS共有に移動できました。一度に最大1,500万個のファイルを移動できるようになりました。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html#moving-source-files-to-an-nfs-share["BlueXPによる分類を使用したソースファイルの移動の詳細については、こちらをご覧ください"]。



=== SharePoint Onlineファイルへのアクセス権を持つユーザーの数を表示する機能

フィルタ「アクセス権を持つユーザー数」で、SharePoint Onlineリポジトリに保存されているファイルがサポートされるようになりました。これまでは、CIFS共有上のファイルのみがサポートされていました。現時点では、Active DirectoryベースでないSharePointグループはこのフィルタにカウントされません。



=== 新しい「部分的成功」ステータスがアクションステータスパネルに追加されました

新しい「Partial Success」ステータスは、BlueXPの分類処理が完了し、一部の項目が失敗し、一部の項目が成功したことを示します（100個のファイルを移動または削除する場合など）。さらに、「終了」ステータスが「成功」に変更されました。以前は、「終了」ステータスに成功した処理と失敗した処理が表示されることがありました。現在、「Success」ステータスは、すべての項目に対するすべてのアクションが成功したことを意味します。 https://docs.netapp.com/us-en/bluexp-classification/task-view-compliance-actions.html["アクションステータスパネルの表示方法を参照してください"]。



== 2023年1月9日（バージョン1.19）



=== 機密データが含まれ、過度に許容されるファイルのグラフを表示する機能

Governanceダッシュボードには、機密データ（機密性の高い個人データと機密性の高い個人データの両方を含む）を含むファイルのヒートマップを提供するnew_sensitive DataおよびWide Permissive_areaが追加されています。これにより、機密データを含むリスクがある場所を確認できます。 https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html#data-listed-by-sensitivity-and-wide-permissions["詳細はこちら。"]。



=== Data Investigationページでは、3つの新しいフィルタを使用できます

[データ調査]ページに表示する結果を絞り込むための新しいフィルタを使用できます。

* 「アクセス権を持つユーザの数」フィルタは、特定の数のユーザに対して開かれているファイルやフォルダを表示します。数値の範囲を選択して結果を絞り込むことができます。たとえば、51~100ユーザがアクセスできるファイルを確認できます。
* 「作成日時」、「検出日時」、「最終変更日時」、「最終アクセス日時」の各フィルタを使用して、事前に定義された日範囲だけを選択するのではなく、カスタムの日付範囲を作成できるようになりました。たとえば、「作成日時」が6か月を超えているファイルや、「最終更新日時」が「過去10日間」の日付になっているファイルを探すことができます。
* 「ファイルパス」フィルタで、フィルタリングされたクエリ結果から除外するパスを指定できるようになりました。対象に含めるデータと除外するデータの両方のパスを入力すると、BlueXPの分類によって、対象に含めるパス内のすべてのファイルが最初に検出され、除外するパスからファイルが削除されて結果が表示されます。


https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#filtering-data-in-the-data-investigation-page["データの調査に使用できるすべてのフィルタのリストを確認します"]。



=== BlueXPの分類では、日本の個人番号を識別できます

BlueXPの分類では、日本語の個人番号（「マイナンバー」とも呼ばれます）を含むファイルを特定して分類できます。これには、個人用電話番号と会社用電話番号の両方が含まれます。 https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["BlueXPの分類によってデータから特定できるすべてのタイプの個人データを確認できます"]。



== 2022年12月11日（バージョン1.18）



=== オンプレミスインストールの機能拡張

オンプレミスのデータセンスインストールには、次の拡張機能が追加されています。

* オンプレミスホストでインストールを開始する前に、いくつかの前提条件が確認されます。これにより、ホストシステムにデータセンスソフトウェアを100%インストールできる状態になります。
+
** の十分なスペースをテストします `/var/lib/docker`、 `/tmp`および `/opt`
** 必要なすべてのフォルダについて、関連する権限をテストします


* [構成]ページの[作業環境]セクションに、_Working Environment ID_と_Scanner Group_nameが表示されるようになりました。複数のData Senseホストを使用して、データソースをスキャンする処理能力を追加する場合は、Working Environment IDを知っておく必要があります。
* また、設定ページの新しいセクションには、設定したスキャナグループと各グループにあるスキャナノードが表示されます。


https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["1台のホストサーバと複数のホストにデータセンスをインストールする方法については、こちらをご覧ください"]。



== 2022年11月13日（バージョン1.17）



=== オンプレミスのSharePointアカウントのスキャンがサポートされます

データセンスで、SharePoint OnlineアカウントとSharePointオンプレミスアカウント(SharePoint Server)の両方をスキャンできるようになりました。SharePointを自分のサーバー、またはインターネットにアクセスできないサイトにインストールする必要がある場合は、これらのアカウントのユーザーファイルをデータ検出でスキャンできるようになりました。 https://docs.netapp.com/us-en/bluexp-classification/task-scanning-sharepoint.html#adding-a-sharepoint-on-premise-account["詳細はこちら。"^]。



=== 複数のディレクトリ（フォルダまたは共有）を再スキャンする機能

これで、複数のディレクトリ（フォルダまたは共有）をただちに再スキャンして、変更がシステムに反映されるようになります。これにより、特定のデータを再スキャンする際に、他のデータよりも優先順位を付けることができます。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["ディレクトリを再スキャンする方法を参照してください"^]。



=== オンプレミスの「スキャナ」ノードを追加して、特定のデータソースをスキャンする機能

データセンスをオンプレミス環境にインストールしている場合、特定のデータソースをスキャンするためにスキャン処理能力がさらに必要になることがわかったときは、「スキャナ」ノードを追加して、それらのデータソースをスキャンするように割り当てることができます。マネージャノードをインストールした直後にスキャナノードを追加することも、後でスキャナノードを追加することもできます。

必要に応じて、スキャンするデータソースに物理的に近いホストシステムにスキャナノードをインストールできます。スキャナノードがデータに近いほど、データのスキャン時のネットワークレイテンシができるだけ低減されるため、データの読み取り速度が向上します。 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html#add-scanner-nodes-to-an-existing-deployment["スキャナノードをインストールして他のデータソースをスキャンする方法を参照してください"^]。



=== オンプレミスのインストーラが、インストールを開始する前に事前チェックを実行できるようになりました

LinuxシステムにData Senseをインストールする場合、実際のインストールを開始する前に、システムが必要な要件（CPU、RAM、容量、ネットワークなど）をすべて満たしているかどうかを確認します。これにより、インストールに時間を費やす前に*問題をキャッチできます。



== 2022年9月6日（バージョン1.16）



=== ファイルの変更を反映するために、リポジトリをすぐに再スキャンできます

変更がシステムに反映されるように特定のリポジトリをただちに再スキャンする必要がある場合は、リポジトリを選択して再スキャンします。これにより、特定のデータを再スキャンする際に、他のデータよりも優先順位を付けることができます。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["ディレクトリを再スキャンする方法を参照してください"^]。



=== [データ調査]ページの[データスキャン]ステータスの新しいフィルタ

[分析ステータス]フィルタを使用すると、データセンススキャンの特定の段階にあるファイルを一覧表示できます。オプションを選択して、「*最初のスキャンを保留*」、「*完了*スキャン中」、「*再スキャンを保留中*」、または「スキャンに失敗*」のファイルのリストを表示できます。

https://docs.netapp.com/us-en/bluexp-classification/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["データの調査に使用できるすべてのフィルタのリストを確認します"^]。



=== データ主体は、スキャンで見つかった「個人データ」の一部と見なされるようになりました

データセンスは、コンプライアンスダッシュボードに表示される個人結果の一部として、データ主体を認識するようになりました。また、［調査］ページで検索を実行するときに、［個人データ］の［データ主体］を選択して、データ主体を含むファイルのみを表示することもできます。



=== データ検出ブレッドクラムファイルは、スキャンで検出された「カテゴリ」の一部と見なされるようになりました

データ検出では、階層リンクファイルがコンプライアンスダッシュボードに表示されるカテゴリの一部として認識されるようになりました。これらは、ソースの場所からNFS共有にファイルを移動するときにData Senseによって作成されるファイルです。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html#moving-source-files-to-an-nfs-share["ブレッドクラムファイルの作成方法の詳細については、こちらをご覧ください"^]。

また、[調査]ページで検索を実行するときに、[カテゴリ]の[データセンスパンくずリスト]を選択して、データセンスブレッドクラムファイルのみを表示することもできます。



== 2022年8月7日（バージョン1.15）



=== ニュージーランドの5つの新しいタイプの個人データは、データセンスによって識別されます

データセンスでは、次の種類のデータを含むファイルを識別および分類できます。

* ニュージーランド銀行口座番号
* ニュージーランド・ドライバーのライセンス番号
* ニュージーランドIRD番号（税ID）
* ニュージーランドNHI（National Health Index）番号
* ニュージーランドパスポート番号


link:reference-private-data-categories.html#types-of-personal-data["データで特定できるすべての種類の個人データを表示します"]。



=== ブレッドクラムファイルを追加して、ファイルが移動された理由を示す機能

データ検出機能を使用してソースファイルをNFS共有に移動する際に、移動したファイルの場所にブレッドクラムファイルを残すことができるようになりました。ブレッドクラムファイルは、ファイルが元の場所から移動された理由をユーザーが理解するのに役立ちます。移動されたファイルごとに、システムはという名前のソースの場所にブレッドクラムファイルを作成します `<filename>-breadcrumb-<date>.txt` ファイルが移動された場所とファイルを移動したユーザーを表示します。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html#moving-source-files-to-an-nfs-share["詳細はこちら。"^]。



=== ディレクトリにある個人データと機密性の高い個人データは、調査結果に表示されます

[データ調査]ページに、個人データと、ディレクトリ（フォルダおよび共有）内で検出された機密性の高い個人データの結果が表示されるようになりました。 https://docs.netapp.com/us-en/bluexp-classification/task-controlling-private-data.html#viewing-files-that-contain-personal-data["例を参照してください"^]。



=== 分類に成功したボリューム、バケットなどの数のステータスを表示します

データ検出でスキャンしている個々のリポジトリ（ボリューム、バケットなど）を表示したときに、マッピングされているリポジトリの数と「分類済み」の数が表示されるようになりました。すべてのデータに対してAIの完全な識別が実行されるため、分類にかかる時間が長くなります。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#viewing-the-scan-status-for-your-repositories["この情報の表示方法については、を参照してください"^]。



=== これで、データの中でデータを識別するカスタムパターンを追加できるようになりました

将来のスキャンでデータセンスが識別するカスタムの「個人データ」を追加するには、2つの方法があります。これにより、機密性の高いデータがすべての組織のファイル内に存在する場所に関する全体像を確認できます。

* テキストファイルからカスタムキーワードを追加できます。
* 正規表現（regex）を使用してパーソナルパターンを追加できます。


これらのキーワードとパターンは、データ検出ですでに使用されている既存の定義済みパターンに追加され、結果は[個人パターン]セクションに表示されます。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["詳細はこちら。"^]。



== 2022年7月6日（バージョン1.14）



=== これで、ディレクトリにアクセスできるユーザとグループを表示できます

これまでは、個々のファイルに付与されているオープンアクセス権のタイプを表示できました。これで、ディレクトリ（フォルダおよびファイル共有）にアクセスできるすべてのユーザまたはグループ、およびディレクトリにアクセスできる権限のタイプのリストが表示されます。 https://docs.netapp.com/us-en/bluexp-classification/task-controlling-private-data.html#viewing-permissions-for-files-and-directories["フォルダおよびファイル共有にアクセスできるユーザとグループを表示する方法について説明します"]。



=== リポジトリのスキャンを一時停止すると'特定のコンテンツのスキャンを一時的に停止できます

スキャンを一時停止した場合、ボリュームやバケットに対する追加や変更はデータスキャンで今後実行されませんが、現在の結果はすべてシステムで確認できます。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#pausing-and-resuming-scanning-for-a-repository["スキャンを一時停止および再開する方法を参照してください"]。



=== 3つの追加状態からのUSドライバーのライセンスデータは、データセンスで識別できます

データセンスは、インディアナ、ニューヨーク、テキサスの運転免許証データを含むファイルを識別して分類できます。 link:reference-private-data-categories.html#types-of-personal-data["データで特定できるすべての種類の個人データを表示します"]。



=== ポリシーは、検索条件に一致するディレクトリを返すようになりました

以前は、カスタムポリシーを作成したときに、検索条件に一致したファイルが結果に表示されていました。これで、クエリに一致するディレクトリ（フォルダおよびファイル共有）も結果に表示されます。 https://docs.netapp.com/us-en/bluexp-classification/task-org-private-data.html#creating-custom-policies["ポリシーの作成の詳細については、こちらをご覧ください"]。



=== データセンスでは、一度に最大100,000個のファイルを移動できます

スキャンしたデータソースからNFS共有へのファイル移動にData Senseを使用する場合は、ファイルの最大数が100、000ファイルに増加しています。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html#moving-source-files-to-an-nfs-share["データセンスを使用してファイルを移動する方法をご覧ください"]。



== 2022年6月12日（バージョン1.13.1）



=== Data Investigationページから結果を.jsonレポートとしてダウンロードできるようになりました

[データ調査]ページでデータをフィルタリングした後、データを.jsonファイルに保存してNFS共有にエクスポートできます。これにより、ローカルシステム上の.csvファイルにデータを保存することができます。データセンスにエクスポートアクセスのための正しい権限があることを確認します。 https://docs.netapp.com/us-en/bluexp-classification/task-generating-compliance-reports.html#data-investigation-report["Data Investigationページからレポートを作成する方法を参照してください"]。



=== データセンスUIからデータセンスをアンインストールする機能

Data Senseをアンインストールして、ソフトウェアをホストから完全に削除することができます。クラウドの導入の場合は、Data Senseが導入されていた仮想マシン/インスタンスを削除します。インスタンスを削除すると、データセンスがスキャンしたインデックス情報がすべて完全に削除されます。 https://docs.netapp.com/us-en/bluexp-classification/task-uninstall-data-sense.html["方法を参照してください"]。



=== 監査ログを使用して、データ検出によって実行されたアクションの履歴を追跡できるようになりました

監査ログは、データがスキャンしているすべての作業環境およびデータソースから、ファイルに対してデータが実行した管理アクティビティを追跡します。アクティビティには、ユーザが生成するアクティビティ（ファイルの削除、ポリシーの作成など）と生成されるポリシー（ファイルにラベルを自動的に追加するアクティビティ、ファイルを自動的に削除するアクティビティなど）があります。

https://docs.netapp.com/us-en/bluexp-classification/task-audit-data-sense-actions.html["監査ログの詳細を確認してください"]。



=== [データ調査]ページの重要な識別子の数に対する新しいフィルタ

「Number of identifiers（識別子の数）」フィルタを使用すると、個人データと機密性の高い個人データの両方を含む、一定数の機密識別子を持つファイルをリストできます。1-10や501-1000などの範囲を選択すると、その数の機密識別子を含むファイルのみを表示できます。

https://docs.netapp.com/us-en/bluexp-classification/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["データの調査に使用できるすべてのフィルタのリストを確認します"]。



=== これで、作成した既存のポリシーを編集できるようになります

以前に作成したカスタムポリシーに変更を加える必要がある場合は、新しいポリシーを作成する代わりにポリシーを編集できるようになりました。 https://docs.netapp.com/us-en/bluexp-classification/task-org-private-data.html#editing-policies["ポリシーの編集方法については、を参照してください"]。



== 2022年5月11日（バージョン1.12.1）



=== Google Driveアカウントでのデータスキャンのサポートが追加されました

Googleドライブアカウントからドキュメントやファイルをスキャンするために、Googleドライブアカウントをデータセンスに追加できるようになりました。 https://docs.netapp.com/us-en/bluexp-classification/task-scanning-google-drive.html["Googleドライブアカウントをスキャンする方法をご覧ください"]。

データセンスは、に加えて、Googleドキュメントスイート（ドキュメント、シート、スライド）からGoogleファイルタイプ内の個人識別情報（PII）を識別できます https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-files["既存のファイルタイプ"]。



=== [データ調査]ページに追加されたディレクトリレベルビュー

すべてのファイルおよびデータベースのデータを表示およびフィルタリングするだけでなく、[データ調査]ページのフォルダおよび共有内のすべてのデータに基づいてデータを表示およびフィルタリングできるようになりました。ディレクトリには、スキャンされたCIFS共有とNFS共有、OneDrive、SharePoint、Google Driveフォルダのインデックスが作成されます。これで、権限を表示し、ディレクトリレベルでデータを管理できるようになりました。 https://docs.netapp.com/us-en/bluexp-classification/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["スキャンしたデータのディレクトリビューを選択する方法を参照してください"]。



=== グループを展開して、ファイルにアクセスする権限を持つユーザー/メンバーを表示します

データセンス権限機能の一部として、ファイルにアクセスできるユーザとグループのリストを表示できるようになりました。各グループを展開すると、グループ内のユーザのリストが表示されます。 https://docs.netapp.com/us-en/bluexp-classification/task-controlling-private-data.html#viewing-permissions-for-files["ファイルに対する読み取り権限または書き込み権限を持つユーザーおよびグループを表示する方法を参照してください"]。



=== 2つの新しいフィルタが[データ調査]ページに追加されました

* 「ディレクトリタイプ」フィルタを使用すると、フォルダまたは共有のみを表示するようにデータを絞り込むことができます。結果は新しい*ディレクトリ*タブに表示されます。
* 「ユーザ/グループの権限」フィルタを使用すると、特定のユーザまたはグループに対する読み取り/書き込み権限があるファイル、フォルダ、および共有を表示できます。複数のユーザまたはグループの名前を選択するか、名前の一部を入力できます。


https://docs.netapp.com/us-en/bluexp-classification/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["データの調査に使用できるすべてのフィルタのリストを確認します"]。



== 2022年4月5日（バージョン1.11.1）



=== オーストラリアの個人データは、データセンスで新たに 4 種類識別できます

データセンスは、オーストラリアTFN (税ファイル番号)、オーストラリア運転免許証番号、オーストラリア医薬品番号、オーストラリアパスポート番号を含むファイルを識別し、分類することができます。 link:reference-private-data-categories.html#types-of-personal-data["データで特定できるすべての種類の個人データを表示します"]。



=== グローバル Active Directory サーバを LDAP サーバとして使用できるようになりました

Data Sense と統合するグローバル Active Directory サーバは、以前にサポートされていた DNS サーバに加えて、 LDAP サーバにすることができます。 link:task-add-active-directory-datasense.html["詳細については、こちらをご覧ください"]。
