= バージョン1.43
:allow-uri-read: 




=== バージョン1.43

このBlueXP  分類リリースの内容は次のとおりです。

.分類スキャンの優先順位付け
BlueXP  分類では、マッピングのみのスキャンに加えて、マップスキャンとスキャンの分類を優先する機能がサポートされており、最初に完了するスキャンを選択できます。MapおよびClassifyスキャンの優先順位付けは、スキャンの開始中および開始前にサポートされます。進行中のスキャンに優先順位を付けることを選択した場合は、マッピングスキャンと分類スキャンの両方に優先順位が付けられます。

詳細については、を参照してください link:https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#prioritize-scans["スキャンの優先順位付け"]。

.カナダの個人識別情報（PII）データカテゴリのサポート
BlueXP  分類スキャンは、カナダのPIIデータカテゴリを識別します。これらのカテゴリには、カナダのすべての州と地域の銀行情報、パスポート番号、社会保険番号、運転免許証番号、健康カード番号が含まれます。

詳細については、を参照してください link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["個人データのカテゴリ"]。

.カスタム分類（プレビュー）
BlueXP  分類では、MapおよびClassifyスキャンのカスタム分類がサポートされます。カスタム分類を使用すると、正規表現を使用して組織固有のデータをキャプチャするようにBlueXP  スキャンを調整できます。この機能は現在プレビュー中です。

詳細については、を参照してください link:https://docs.netapp.com/us-en/bluexp-classification/task-custom-classification.html["カスタム分類の追加"]。

.[保存済み検索]タブ
**Policies**タブの名前が変更されましたlink:https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html["**保存された検索**"]。機能に変更はありません。

.スキャンイベントをBlueXP  タイムラインに送信
BlueXP  分類では、への分類イベント（スキャンの開始時と終了時）の送信がサポートされますlink:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline["BlueXP  のタイムライン"^]。

.セキュリティの更新
* Kerasパッケージが更新され、脆弱性（BDSA-2025-0107およびBDSA-2025-1984）が緩和されました。
* Dockerコンテナの設定が更新されました。コンテナは、未加工のネットワークパケットを作成するためのホストのネットワークインターフェイスにアクセスできなくなります。不要なアクセスを減らすことで、潜在的なセキュリティリスクを軽減します。


.パフォーマンスの強化
RAMの使用量を削減し、BlueXP  分類の全体的なパフォーマンスを向上させるために、コードの拡張が実装されています。

.バグ修正
StorageGRIDスキャンが失敗する原因となったバグ、調査ページのフィルタオプションがロードされない問題、および大量評価のためにダウンロードされないデータ検出評価が修正されました。
