= バージョン1.40
:allow-uri-read: 




=== バージョン1.40

このBlueXP  分類リリースには、次の更新が含まれています。

.RHEL 9.5のサポート
このリリースでは、以前のサポートバージョンに加えて、Red Hat Enterprise Linux v9.5もサポートされます。これは、ダークサイトの導入を含む、BlueXP  分類の手動オンプレミスインストールに適用されます。

次のオペレーティングシステムでは、Podmanコンテナエンジンを使用する必要があり、BlueXP  分類バージョン1.30以降が必要です。Red Hat Enterprise Linuxバージョン8.8、8.10、9.0、9.1、9.2、9.3、9.4、9.5。

.スキャンの優先順位付け
スキャン設定では、最も重要なスキャンに優先順位を付けて、他のスキャンよりも先に実行することができます。この機能は、多数の作業環境があり、優先度の高いスキャンが最初に正常に実行されていることを確認したい場合に役立ちます。

スキャンには次の2種類があります。

* *マッピングのみのスキャン*では、データの概要のみが表示されます。データソースでは、ファイルにアクセスしてデータを参照できないため、マッピングは短時間で完了します。
* * Map and Classify *スキャンを使用すると、データを詳細にスキャンできます。


マッピングのみのスキャンを使用すると、データをすばやくスキャンして詳細な調査が必要なデータソースを特定し、あとで必要なデータソースまたはボリュームに対してのみスキャンと分類を有効にすることができます。

優先度は、マッピングのみのスキャンにのみ割り当てられ、マップスキャンと分類スキャンには割り当てられません。

優先度はデフォルトで1に設定されており、1~10の任意の数値に変更できます。数値が小さいほど、優先度が高くなります。優先度を設定しない場合、スキャンには優先度5が割り当てられます。

優先度を変更するには、次の手順を実行します。

. BlueXP  分類メニューから*設定*を選択します。
. 優先順位を付けるリソースを選択します。
. [Actions...]オプションから、*[Prioritize scan]*を選択します。


.スキャンの再試行
このリリースでは、失敗したスキャンを再試行できます。この機能は、ネットワークの停止などの一時的な問題が原因でスキャンに失敗した場合に役立ちます。再設定せずにスキャンを再試行できます。

スキャンを再試行するには、次の手順を実行します。

. BlueXP  分類メニューから*設定*を選択します。
. 次のいずれかを実行します。
+
** 失敗したスキャンをすべて再試行するには、*[すべてのスキャンを再試行]*を選択します。
** 特定のスキャンを再試行するには、リソースを選択し、[アクション]オプションから*[スキャンの再試行]*を選択します。




スキャンは、元のスキャンと同じ設定で再試行されます。スキャンが再度失敗した場合は、必要に応じて何度でも再試行できます。
