= バージョン1.40
:allow-uri-read: 




=== バージョン1.40

このBlueXP  分類リリースには、次の更新が含まれています。

.RHEL 9.5のサポート
このリリースでは、以前のサポートバージョンに加えて、Red Hat Enterprise Linux v9.5もサポートされます。これは、ダークサイトの導入を含む、BlueXP  分類の手動オンプレミスインストールに適用されます。

次のオペレーティングシステムでは、Podmanコンテナエンジンを使用する必要があり、BlueXP  分類バージョン1.30以降が必要です。Red Hat Enterprise Linuxバージョン8.8、8.10、9.0、9.1、9.2、9.3、9.4、9.5。

.マッピングのみのスキャンの優先順位付け
マッピングのみのスキャンを実行する場合は、最も重要なスキャンに優先順位を付けることができます。この機能は、多数の作業環境があり、優先度の高いスキャンを先に完了させたい場合に役立ちます。

デフォルトでは、スキャンは開始順序に基づいてキューに入れられます。スキャンに優先順位を付ける機能により、スキャンをキューの先頭に移動できるようになりました。複数のスキャンに優先順位を付けることができます。優先順位は、先入れ先出し順で指定されます。つまり、最初に優先順位を付けたスキャンがキューの先頭に移動し、2番目に優先順位を付けたスキャンがキューの2番目に移動します。

優先度は1回だけ付与されます。マッピングデータの自動再スキャンは、デフォルトの順序で実行されます。

優先順位付けはに限定されlink:concept-cloud-compliance.html["マッピングのみのスキャン"]、マップスキャンおよび分類スキャンでは使用できません。

詳細については、を参照してください link:task-managing-repo-scanning.html#prioritize-scans["スキャンの優先順位付け"]。

.すべてのスキャンを再試行
BlueXP  分類では、失敗したすべてのスキャンをバッチ再試行できるようになりました。

**すべて再試行**機能を使用して、バッチ操作でスキャンを再試行できるようになりました。ネットワークの停止などの一時的な問題が原因で分類スキャンが失敗した場合は、個 々 に再試行するのではなく、ボタン1つですべてのスキャンを同時に再試行できます。スキャンは必要に応じて何度でも再試行できます。

すべてのスキャンを再試行するには：

. BlueXP  分類メニューから*設定*を選択します。
. 失敗したスキャンをすべて再試行するには、*[すべてのスキャンを再試行]*を選択します。


.カテゴリ化モデルの精度の向上
の機械学習モデルの精度はlink:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["事前定義されたカテゴリ"]11%向上しました。
